import type { PlanningRegistry, PlanningRegistryItem } from "./types";

function career(
  item: Omit<PlanningRegistryItem, "reelAffinity"> & { reelAffinity?: string[] }
): PlanningRegistryItem {
  return { ...item, reelAffinity: item.reelAffinity ?? [] };
}

export const planningRegistry: PlanningRegistry = {
  "ux-designer": career({
    slug: "ux-designer",
    family: "design",
    titleTh: "Product / UX Designer",
    titleEn: "Product / UX Designer",
    facets: ["creativity", "helping", "autonomy", "human-contact"],
    capabilities: ["user-research", "prototyping", "storytelling"],
    adjacent: ["product-manager", "graphic-designer", "software-engineer"],
    contrast: ["ai-engineer", "data-scientist"],
    reelAffinity: ["tech-beyond-software"],
  }),
  "ai-engineer": career({
    slug: "ai-engineer",
    family: "engineering",
    titleTh: "AI Engineer",
    titleEn: "AI Engineer",
    facets: ["innovation", "analytical", "growth", "income"],
    capabilities: ["systems-thinking", "experimentation", "coding"],
    adjacent: ["data-scientist", "software-engineer", "product-manager"],
    contrast: ["ux-designer", "teacher"],
    reelAffinity: ["tech-beyond-software"],
    pathLabHref: "/seeds/pathlab/ai-engineer",
  }),
  "product-manager": career({
    slug: "product-manager",
    family: "product",
    titleTh: "Product Manager",
    titleEn: "Product Manager",
    facets: ["autonomy", "growth", "human-contact", "innovation"],
    capabilities: ["systems-thinking", "user-research", "storytelling"],
    adjacent: ["ux-designer", "software-engineer", "marketing-specialist"],
    contrast: ["data-scientist", "graphic-designer"],
    reelAffinity: ["tech-beyond-software"],
  }),
  "data-scientist": career({
    slug: "data-scientist",
    family: "data",
    titleTh: "Data Scientist",
    titleEn: "Data Scientist",
    facets: ["analytical", "growth", "income", "innovation"],
    capabilities: ["experimentation", "systems-thinking", "research"],
    adjacent: ["ai-engineer", "software-engineer", "financial-analyst"],
    contrast: ["ux-designer", "marketing-specialist"],
    reelAffinity: ["tech-beyond-software"],
  }),
  "software-engineer": career({
    slug: "software-engineer",
    family: "engineering",
    titleTh: "Software Engineer",
    titleEn: "Software Engineer",
    facets: ["analytical", "autonomy", "growth", "income"],
    capabilities: ["coding", "systems-thinking", "experimentation"],
    adjacent: ["ai-engineer", "data-scientist", "ux-designer"],
    contrast: ["product-manager", "teacher"],
    reelAffinity: ["tech-beyond-software"],
  }),
  cybersecurity: career({
    slug: "cybersecurity",
    family: "security",
    titleTh: "ความมั่นคงปลอดภัยทางไซเบอร์",
    titleEn: "Cybersecurity",
    facets: ["analytical", "stability", "growth", "helping"],
    capabilities: ["risk-analysis", "systems-thinking", "incident-response"],
    adjacent: ["devops-sre", "software-engineer", "it-support-sysadmin"],
    contrast: ["ai-engineer", "fashion-designer"],
    reelAffinity: ["tech-beyond-software"],
  }),
  "devops-sre": career({
    slug: "devops-sre",
    family: "infrastructure",
    titleTh: "DevOps / SRE",
    titleEn: "DevOps / Site Reliability Engineer",
    facets: ["analytical", "autonomy", "stability", "growth"],
    capabilities: ["systems-thinking", "automation", "incident-response"],
    adjacent: ["software-engineer", "cybersecurity", "it-support-sysadmin"],
    contrast: ["data-scientist", "marketing-strategist"],
    reelAffinity: ["tech-beyond-software"],
  }),
  "qa-engineer": career({
    slug: "qa-engineer",
    family: "quality-engineering",
    titleTh: "วิศวกรทดสอบซอฟต์แวร์",
    titleEn: "QA Engineer",
    facets: ["analytical", "stability", "helping", "growth"],
    capabilities: ["quality-thinking", "automation", "communication"],
    adjacent: ["software-engineer", "devops-sre", "cybersecurity"],
    contrast: ["ai-engineer", "fashion-designer"],
    reelAffinity: ["tech-beyond-software"],
  }),
  "it-support-sysadmin": career({
    slug: "it-support-sysadmin",
    family: "infrastructure",
    titleTh: "IT Support / System Admin",
    titleEn: "IT Support / System Administrator",
    facets: ["helping", "human-contact", "stability", "analytical"],
    capabilities: ["troubleshooting", "systems-thinking", "communication"],
    adjacent: ["devops-sre", "cybersecurity", "software-engineer"],
    contrast: ["fashion-designer", "data-scientist"],
  }),
  accountant: career({
    slug: "accountant",
    family: "finance",
    titleTh: "นักบัญชี",
    titleEn: "Accountant",
    facets: ["stability", "analytical", "income", "growth"],
    capabilities: ["financial-reasoning", "quality-thinking", "decision-making"],
    adjacent: ["data-scientist", "financial-analyst"],
    contrast: ["fashion-designer", "marketing-strategist"],
  }),
  "fashion-designer": career({
    slug: "fashion-designer",
    family: "design",
    titleTh: "นักออกแบบแฟชั่น",
    titleEn: "Fashion Designer",
    facets: ["creativity", "autonomy", "flexibility", "innovation"],
    capabilities: ["visual-storytelling", "prototyping", "research"],
    adjacent: ["marketing-strategist", "model", "graphic-designer"],
    contrast: ["accountant", "cybersecurity"],
  }),
  "marketing-strategist": career({
    slug: "marketing-strategist",
    family: "business",
    titleTh: "นักกลยุทธ์การตลาด",
    titleEn: "Marketing Strategist",
    facets: ["creativity", "human-contact", "growth", "analytical"],
    capabilities: ["storytelling", "experimentation", "research"],
    adjacent: ["fashion-designer", "data-scientist", "marketing-specialist"],
    contrast: ["accountant", "devops-sre"],
  }),
  "mechanical-engineer": career({
    slug: "mechanical-engineer",
    family: "engineering",
    titleTh: "วิศวกรเครื่องกล",
    titleEn: "Mechanical Engineer",
    facets: ["analytical", "innovation", "stability", "growth"],
    capabilities: ["systems-thinking", "prototyping", "problem-solving"],
    adjacent: ["software-engineer", "qa-engineer"],
    contrast: ["marketing-strategist", "model"],
  }),
  "medical-technologist": career({
    slug: "medical-technologist",
    family: "healthcare",
    titleTh: "นักเทคนิคการแพทย์",
    titleEn: "Medical Technologist",
    facets: ["helping", "analytical", "stability", "growth"],
    capabilities: ["quality-thinking", "research", "decision-making"],
    adjacent: ["data-scientist", "nurse"],
    contrast: ["fashion-designer", "marketing-strategist"],
  }),
  model: career({
    slug: "model",
    family: "media",
    titleTh: "นางแบบ / นายแบบ",
    titleEn: "Model",
    facets: ["creativity", "flexibility", "human-contact", "autonomy"],
    capabilities: ["visual-storytelling", "communication", "adaptability"],
    adjacent: ["fashion-designer", "marketing-strategist"],
    contrast: ["accountant", "devops-sre"],
  }),
  "graphic-designer": career({
    slug: "graphic-designer",
    family: "design",
    titleTh: "Graphic Designer",
    titleEn: "Graphic Designer",
    facets: ["creativity", "flexibility", "autonomy"],
    capabilities: ["visual-storytelling", "prototyping", "storytelling"],
    adjacent: ["ux-designer", "marketing-specialist", "photographer"],
    contrast: ["data-scientist", "financial-analyst"],
    reelAffinity: ["tech-beyond-software"],
  }),
  "marketing-specialist": career({
    slug: "marketing-specialist",
    family: "business",
    titleTh: "Marketing Specialist",
    titleEn: "Marketing Specialist",
    facets: ["creativity", "growth", "human-contact", "flexibility"],
    capabilities: ["storytelling", "experimentation", "research"],
    adjacent: ["product-manager", "content-writer", "graphic-designer"],
    contrast: ["software-engineer", "financial-analyst"],
  }),
  teacher: career({
    slug: "teacher",
    family: "education",
    titleTh: "ครู / นักการศึกษา",
    titleEn: "Teacher",
    facets: ["helping", "human-contact", "stability", "creativity"],
    capabilities: ["facilitation", "storytelling", "coaching"],
    adjacent: ["content-writer", "ux-designer", "hr-recruiter"],
    contrast: ["ai-engineer", "data-scientist"],
  }),
  nurse: career({
    slug: "nurse",
    family: "healthcare",
    titleTh: "พยาบาล",
    titleEn: "Nurse",
    facets: ["helping", "human-contact", "stability", "growth"],
    capabilities: ["care", "coordination", "decision-making"],
    adjacent: ["teacher", "customer-service-representative"],
    contrast: ["software-engineer", "graphic-designer"],
  }),
  "financial-analyst": career({
    slug: "financial-analyst",
    family: "finance",
    titleTh: "Financial Analyst",
    titleEn: "Financial Analyst",
    facets: ["analytical", "income", "stability", "growth"],
    capabilities: ["research", "systems-thinking", "decision-making"],
    adjacent: ["data-scientist", "accountant", "product-manager"],
    contrast: ["graphic-designer", "teacher"],
  }),
  "content-writer": career({
    slug: "content-writer",
    family: "media",
    titleTh: "Content Writer",
    titleEn: "Content Writer",
    facets: ["creativity", "flexibility", "autonomy", "helping"],
    capabilities: ["storytelling", "research", "communication"],
    adjacent: ["journalist", "marketing-specialist", "teacher"],
    contrast: ["ai-engineer", "financial-analyst"],
  }),
  journalist: career({
    slug: "journalist",
    family: "media",
    titleTh: "Journalist",
    titleEn: "Journalist",
    facets: ["helping", "human-contact", "autonomy", "creativity"],
    capabilities: ["research", "storytelling", "communication"],
    adjacent: ["content-writer", "photographer", "teacher"],
    contrast: ["software-engineer", "accountant"],
  }),
  photographer: career({
    slug: "photographer",
    family: "media",
    titleTh: "Photographer",
    titleEn: "Photographer",
    facets: ["creativity", "flexibility", "human-contact", "autonomy"],
    capabilities: ["visual-storytelling", "communication", "observation"],
    adjacent: ["graphic-designer", "journalist", "marketing-specialist"],
    contrast: ["data-scientist", "accountant"],
  }),
};

export function getRegistryItem(slug: string): PlanningRegistryItem | undefined {
  return planningRegistry[slug];
}
