-- Enhance career_survival seed data with Thai-specific sources and market intelligence insights
-- Idempotent: updates existing rows by slug, or inserts if not exists
-- Keeps tier, reasoning, and escape_route_slug unchanged

INSERT INTO public.career_survival (slug, aliases, tier, reasoning, sources, escape_route_slug, insights)
VALUES
  (
    'software-engineer',
    ARRAY['programmer', 'coder', 'developer', 'software developer'],
    'growing',
    'Demand for software engineers continues to outpace supply globally. AI coding assistants augment productivity but do not replace the architectural reasoning, debugging, and systems design that senior engineers perform. The U.S. Bureau of Labor Statistics projects 25% growth in software development roles through 2032.',
    '[{"title":"Occupational Outlook Handbook: Software Developers","url":"https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"TCAS รอบที่ 3 : คณะวิศวกรรมศาสตร์ คอมพิวเตอร์ จุฬาฯ","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"รายงานเงินเดือน Software Engineer ประจำปี 2024","url":"https://www.jobthai.com/salary-report/software-engineer","author":"JobThai","date":"2024-12-01"},{"title":"Thailand Digital Outlook 2024","url":"https://www.depa.or.th/th/article/digital-outlook-2024","author":"สำนักงานส่งเสริมเศรษฐกิจดิจิทัล (DEPA)","date":"2024-03-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Python, JavaScript/TypeScript, SQL, Git, Docker, and cloud fundamentals (AWS/Azure). AI tool fluency (Copilot, ChatGPT API) is now expected.","priority":1},{"category":"education","content":"Computer Engineering or Software Engineering at Chulalongkorn, Kasetsart, KMUTT, or Mahidol. TCAS รอบ 3 (Portfolio) is the most common entry for strong candidates.","priority":1},{"category":"certifications","content":"AWS Certified Developer, Google Associate Cloud Engineer, or Microsoft Azure Fundamentals. Thai companies increasingly value cloud certs for senior roles.","priority":3},{"category":"portfolio","content":"GitHub with 3+ production-grade projects (full-stack web app, mobile app, or API). Contributions to open source are a strong differentiator in Thailand.","priority":2},{"category":"market","content":"Extremely high demand in Bangkok fintech (SCB, KBANK, LINE BK), e-commerce (Shopee, Lazada), and startups (Agoda, Flash Express). Growing remote opportunities.","priority":1},{"category":"timeline","content":"4-year degree + 1-2 years junior experience → mid-level (50-80k). Senior roles (100k+) typically require 4-6 years.","priority":2},{"category":"salary","content":"Entry: 25,000-40,000 THB. Mid-level: 50,000-90,000 THB. Senior: 100,000-200,000+ THB. International remote roles can pay 2-3x local rates.","priority":1},{"category":"competition","content":"Very competitive for top tech companies and international firms. Moderate for SMEs and startups. Strong portfolio and English fluency are key differentiators.","priority":2}]'::jsonb
  ),
  (
    'data-scientist',
    ARRAY['data analyst', 'machine learning engineer', 'ml engineer', 'data engineer'],
    'growing',
    'Organizations are investing heavily in AI and analytics, driving sustained demand for data scientists who can translate raw data into strategic decisions. The role requires domain expertise, statistical rigor, and communication skills that are difficult to automate. BLS projects 35% growth for data scientist positions through 2032.',
    '[{"title":"Occupational Outlook Handbook: Data Scientists","url":"https://www.bls.gov/ooh/math/data-scientists.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"The Age of AI: Promise and Peril","url":"https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai","author":"McKinsey & Company","date":"2023-08-01"},{"title":"รายงานเงินเดือน Data Scientist ประจำปี 2024","url":"https://www.jobthai.com/salary-report/data-scientist","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะวิทยาศาสตร์และเทคโนโลยี สถิติ/ดาต้า ไซเอนซ์","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand AI Readiness Index 2024","url":"https://www.nia.or.th/th/ai-readiness","author":"สำนักงานนวัตกรรมแห่งชาติ (NIA)","date":"2024-06-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Python, SQL, statistics, machine learning (scikit-learn, TensorFlow/PyTorch), data visualization (Tableau, Power BI). Strong math foundation is essential.","priority":1},{"category":"education","content":"Statistics, Computer Science, or Data Science at Chulalongkorn, Thammasat, Mahidol, or Kasetsart. Some roles accept Math/Physics graduates with strong coding skills.","priority":1},{"category":"certifications","content":"Google Data Analytics Certificate, AWS Machine Learning Specialty, or Databricks Data Engineer. Kaggle Competitions Expert/Master badge is highly valued.","priority":3},{"category":"portfolio","content":"Kaggle competitions (top 10%), GitHub with end-to-end ML projects, and a technical blog explaining your methodology. Thai employers love seeing applied local datasets.","priority":2},{"category":"market","content":"High demand in banking (SCB, KBANK), telecom (AIS, True), e-commerce, and consulting (McKinsey, BCG). Government agencies are also building data teams.","priority":1},{"category":"timeline","content":"4-year degree + 1-2 years as Data Analyst → Junior Data Scientist (3-5 years total for mid-level). PhD accelerates research roles but is not required for industry.","priority":2},{"category":"salary","content":"Entry: 30,000-45,000 THB. Mid-level: 60,000-100,000 THB. Senior: 120,000-250,000+ THB. Banking and consulting pay the highest premiums.","priority":1},{"category":"competition","content":"Highly competitive for top roles. Many candidates have overseas degrees or advanced degrees. Differentiate with domain expertise (finance, healthcare, Thai NLP).","priority":2}]'::jsonb
  ),
  (
    'product-manager',
    ARRAY['pm', 'product owner', 'program manager'],
    'growing',
    'Product management sits at the intersection of user needs, business strategy, and technical feasibility. It requires cross-functional leadership, stakeholder negotiation, and ambiguous problem-solving that AI cannot replicate. As tech product complexity grows, so does demand for experienced PMs.',
    '[{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"Product Management in the Age of AI","url":"https://www.mckinsey.com/capabilities/growth-marketing-and-sales/our-insights/product-management-in-the-age-of-ai","author":"McKinsey & Company","date":"2023-11-15"},{"title":"รายงานเงินเดือน Product Manager ประจำปี 2024","url":"https://www.jobthai.com/salary-report/product-manager","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะบริหารธุรกิจ สาขาการตลาด/การจัดการ","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Startup Ecosystem Report 2024","url":"https://www.depa.or.th/th/article/startup-ecosystem-2024","author":"สำนักงานส่งเสริมเศรษฐกิจดิจิทัล (DEPA)","date":"2024-05-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"User research, data-driven decision making, roadmap prioritization (RICE, MoSCoW), Agile/Scrum, SQL for data analysis, and basic technical literacy.","priority":1},{"category":"education","content":"Business Administration, Engineering, or Computer Science at Chulalongkorn, Thammasat, or Mahidol. MBA is increasingly common for senior PM roles at Thai corporates.","priority":2},{"category":"certifications","content":"Certified Scrum Product Owner (CSPO), Google Project Management Certificate, or Pragmatic Institute certifications. Less critical than proven product launches.","priority":3},{"category":"portfolio","content":"Case studies of 2+ products you shipped: problem statement, metrics, trade-offs, and outcomes. Even student projects or hackathon products count if well-documented.","priority":2},{"category":"market","content":"Growing demand in Thai tech startups, fintech, and super-app companies (LINE, Grab, Shopee). Traditional corporates (CP All, Central) are also digitalizing rapidly.","priority":1},{"category":"timeline","content":"4-year degree + 2-3 years in related role (engineer, designer, analyst) → Associate PM → PM (3-5 years total). Senior PM typically requires 6-8 years.","priority":2},{"category":"salary","content":"Entry/Associate: 35,000-50,000 THB. Mid-level: 60,000-100,000 THB. Senior: 120,000-200,000+ THB. Equity is rare in Thailand except at startups.","priority":1},{"category":"competition","content":"Moderate competition. Many PMs transition from engineering or business roles. Bilingual Thai-English and cross-cultural experience are major advantages.","priority":2}]'::jsonb
  ),
  (
    'ux-designer',
    ARRAY['user experience designer', 'interaction designer', 'ui/ux designer', 'product designer'],
    'growing',
    'Human-centered design demands deep empathy, ethnographic research, and iterative prototyping with real users. AI can generate UI mockups but cannot conduct contextual inquiry or synthesize qualitative insights. The field is expanding as companies compete on customer experience.',
    '[{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"Design in the Age of AI","url":"https://www.nngroup.com/articles/ai-ux/","author":"Nielsen Norman Group","date":"2023-06-12"},{"title":"รายงานเงินเดือน UX Designer ประจำปี 2024","url":"https://www.jobthai.com/salary-report/ux-designer","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะสถาปัตยกรรมศาสตร์ สาขานิเทศศาสตร์/ดีไซน์","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Digital Design Trends 2024","url":"https://www.depa.or.th/th/article/digital-design-trends","author":"สำนักงานส่งเสริมเศรษฐกิจดิจิทัล (DEPA)","date":"2024-04-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Figma, user research (interviews, usability testing), prototyping, design systems, information architecture, and basic HTML/CSS understanding.","priority":1},{"category":"education","content":"Design (Communication Arts, Industrial Design) at Chulalongkorn, Silpakorn, or KMUTT. Many successful UX designers come from psychology or HCI backgrounds.","priority":2},{"category":"certifications","content":"Google UX Design Certificate, Nielsen Norman Group UX Master, or IDF courses. Portfolio quality matters far more than certifications in Thailand.","priority":3},{"category":"portfolio","content":"3+ case studies showing full design process: research, wireframes, prototypes, testing, and final designs. Include before/after metrics if possible.","priority":1},{"category":"market","content":"Strong demand in tech startups, fintech, and e-commerce. Large Thai companies (AIS, True, SCB) are building in-house design teams. Freelance market is also growing.","priority":1},{"category":"timeline","content":"3-4 year degree + 1-2 years junior experience → mid-level (50-70k). Senior roles (100k+) typically require 4-6 years and demonstrated leadership.","priority":2},{"category":"salary","content":"Entry: 25,000-40,000 THB. Mid-level: 50,000-80,000 THB. Senior: 90,000-150,000+ THB. Product design at tech companies pays significantly more than agency work.","priority":1},{"category":"competition","content":"Moderate competition. Strong visual portfolio and Thai-English bilingual skills are differentiators. Many designers transition from graphic design or front-end development.","priority":2}]'::jsonb
  ),
  (
    'graphic-designer',
    ARRAY['visual designer', 'digital designer', 'creative designer'],
    'shifting',
    'Generative AI tools like Midjourney and DALL-E are compressing timelines for asset creation, but brands still need human designers for art direction, brand consistency, and creative strategy. The role is shifting from pixel-pushing to creative direction and prompt engineering.',
    '[{"title":"Occupational Outlook Handbook: Graphic Designers","url":"https://www.bls.gov/ooh/arts-and-design/graphic-designers.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"รายงานเงินเดือน Graphic Designer ประจำปี 2024","url":"https://www.jobthai.com/salary-report/graphic-designer","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะสถาปัตยกรรมศาสตร์ สาขาออกแบบนิเทศศาสตร์","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Creative Industry Outlook 2024","url":"https://www.creative-economy.or.th/report-2024","author":"สำนักงานเศรษฐกิจสร้างสรรค์","date":"2024-03-01"}]'::jsonb,
    'ux-designer',
    '[{"category":"skills","content":"Adobe Creative Suite (Illustrator, Photoshop, InDesign), Figma, brand design, typography, and AI tool fluency (Midjourney, Stable Diffusion, Runway). Motion design (After Effects) is a strong plus.","priority":1},{"category":"education","content":"Communication Arts, Visual Communication Design, or Fine Arts at Chulalongkorn, Silpakorn, or Bangkok University. Portfolio-based admission is common.","priority":2},{"category":"certifications","content":"Adobe Certified Professional. Less critical than a strong portfolio. Online courses from Domestika or Skillshare are popular for skill building.","priority":4},{"category":"portfolio","content":"Diverse portfolio showing brand identity, social media campaigns, print, and digital work. Behance or personal website with 8-12 strong pieces.","priority":1},{"category":"market","content":"Steady demand in advertising agencies, in-house marketing teams, and e-commerce. AI is commoditizing basic design work, but brand strategy and art direction remain valuable.","priority":1},{"category":"timeline","content":"3-4 year degree + 1-2 years junior experience → mid-level. Transition to UX design or creative direction is common after 3-5 years.","priority":2},{"category":"salary","content":"Entry: 20,000-30,000 THB. Mid-level: 35,000-55,000 THB. Senior/Art Director: 60,000-100,000+ THB. Freelance rates vary widely (500-3,000 THB/hour).","priority":1},{"category":"competition","content":"High competition for junior roles due to many design graduates. Differentiate with motion design, 3D, or AI-augmented workflows. Strong Thai typography skills are valued locally.","priority":2}]'::jsonb
  ),
  (
    'content-writer',
    ARRAY['copywriter', 'blog writer', 'technical writer', 'freelance writer'],
    'shifting',
    'AI can draft routine copy at scale, but high-quality journalism, thought leadership, and technical writing require subject-matter expertise, original reporting, and editorial judgment. The market is bifurcating: commodity content is automated, while premium writing commands higher rates.',
    '[{"title":"The State of AI in 2023","url":"https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai-in-2023-generative-ais-breakout-year","author":"McKinsey & Company","date":"2023-08-01"},{"title":"Will AI Replace Writers?","url":"https://www.niemanlab.org/2023/06/will-ai-replace-writers/","author":"Nieman Lab","date":"2023-06-15"},{"title":"รายงานเงินเดือน Content Writer ประจำปี 2024","url":"https://www.jobthai.com/salary-report/content-writer","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะอักษรศาสตร์ สาขาวรรณคดี/ภาษาอังกฤษ/นิเทศศาสตร์","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Content Marketing Trends 2024","url":"https://www.thinkwithgoogle.com/intl/en-apac/marketing-strategies/search/content-marketing-thailand-2024/","author":"Google Thailand","date":"2024-02-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Strong Thai and English writing, SEO, storytelling, research, and AI tool fluency (ChatGPT for ideation, NOT for final copy). Niche expertise (tech, finance, health) commands premium rates.","priority":1},{"category":"education","content":"Arts, Communication Arts, English, or Journalism at Chulalongkorn, Thammasat, or TU. Many successful writers have non-writing degrees but deep domain expertise.","priority":3},{"category":"certifications","content":"Google Digital Marketing Certificate, HubSpot Content Marketing Certification. These help but are secondary to writing samples.","priority":4},{"category":"portfolio","content":"Published articles, blog posts, or a Substack/WordPress with 10+ pieces. Technical writers should include documentation samples. Thai + English bilingual portfolio is highly valued.","priority":1},{"category":"market","content":"Content demand is growing in Thai e-commerce, fintech, and SaaS. AI-generated content has created a premium market for original, well-researched writing. Freelance platforms (Fastwork, Fiverr) are popular.","priority":1},{"category":"timeline","content":"No strict timeline. Many start freelancing during university. Full-time roles: 1-2 years junior → mid-level. Senior content strategists need 4-6 years.","priority":2},{"category":"salary","content":"Entry: 20,000-30,000 THB. Mid-level: 35,000-55,000 THB. Senior/Lead: 60,000-90,000 THB. Freelance: 1,000-5,000 THB per article. Technical writers earn 30-50% more.","priority":1},{"category":"competition","content":"Very high competition for general content roles. Niche expertise (crypto, legal tech, medical) and bilingual writing are the main differentiators. AI literacy is now table stakes.","priority":2}]'::jsonb
  ),
  (
    'marketing-specialist',
    ARRAY['digital marketer', 'growth marketer', 'seo specialist', 'marketing manager'],
    'shifting',
    'AI analytics and automated ad bidding have reduced the need for manual campaign optimization, but strategic brand positioning, creative storytelling, and cross-channel orchestration remain human-led. Marketers are upskilling in data literacy and AI tool fluency.',
    '[{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"Marketing and Sales in the Age of AI","url":"https://www.mckinsey.com/capabilities/growth-marketing-and-sales/our-insights/ai-powered-marketing-and-sales-reach-new-heights","author":"McKinsey & Company","date":"2023-05-10"},{"title":"รายงานเงินเดือน Marketing Specialist ประจำปี 2024","url":"https://www.jobthai.com/salary-report/marketing-specialist","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะบริหารธุรกิจ สาขาการตลาด","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Digital Advertising Spend 2024","url":"https://www.thinkwithgoogle.com/intl/en-apac/marketing-strategies/search/digital-ad-spend-thailand-2024/","author":"Google Thailand","date":"2024-03-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Digital marketing (SEO, SEM, social media), data analysis (Google Analytics, SQL), marketing automation, content strategy, and AI tool fluency.","priority":1},{"category":"education","content":"Marketing, Business Administration, or Communication Arts at Chulalongkorn, Thammasat, or Bangkok University. Some roles value statistics or data science backgrounds.","priority":2},{"category":"certifications","content":"Google Analytics Certification, Google Ads Certification, Meta Blueprint, HubSpot Inbound Marketing. These are highly valued in Thai job postings.","priority":2},{"category":"portfolio","content":"Campaign case studies with metrics (CTR, conversion rates, ROI). Include before/after data. Student marketing club projects or internship campaigns count.","priority":2},{"category":"market","content":"Strong demand in e-commerce, fintech, and consumer goods (CP All, Unilever, P&G). SMEs are increasingly hiring digital-first marketers. Agency life is common early in careers.","priority":1},{"category":"timeline","content":"4-year degree + 1-2 years as Marketing Coordinator → Specialist (2-3 years) → Manager (5-7 years). Growth marketing roles may require technical skills earlier.","priority":2},{"category":"salary","content":"Entry: 22,000-35,000 THB. Mid-level: 40,000-70,000 THB. Senior/Manager: 80,000-150,000+ THB. Performance bonuses are common in e-commerce and agencies.","priority":1},{"category":"competition","content":"Moderate to high competition. Many graduates enter through agencies. Data-driven marketers and those with e-commerce/platform experience (Shopee, Lazada, TikTok Shop) are in highest demand.","priority":2}]'::jsonb
  ),
  (
    'accountant',
    ARRAY['bookkeeper', 'tax preparer', 'auditor', 'cpa'],
    'exposed',
    'Cloud accounting software and AI-powered bookkeeping tools can now automate invoice processing, reconciliation, and basic tax preparation. While forensic accounting and strategic advisory remain resilient, entry-level compliance and data-entry roles are rapidly declining.',
    '[{"title":"Occupational Outlook Handbook: Accountants and Auditors","url":"https://www.bls.gov/ooh/business-and-financial/accountants-and-auditors.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"รายงานเงินเดือน Accountant ประจำปี 2024","url":"https://www.jobthai.com/salary-report/accountant","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะบัญชี จุฬาฯ/ธรรมศาสตร์","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Tax Guide for Individuals 2024","url":"https://www.rd.go.th/","author":"กรมสรรพากร","date":"2024-01-01"}]'::jsonb,
    'financial-analyst',
    '[{"category":"skills","content":"Financial reporting, tax compliance, Excel advanced functions, accounting software (QuickBooks, Xero, SAP), and data analysis. AI tool fluency for automation is increasingly important.","priority":1},{"category":"education","content":"Accounting at Chulalongkorn, Thammasat, or Assumption University. CPA Thailand license requires specific coursework and passing the CPA exam.","priority":1},{"category":"certifications","content":"CPA Thailand (สภาวิชาชีพบัญชี), ACCA, or CMA. These are essential for career advancement in Thai accounting firms and MNCs.","priority":1},{"category":"portfolio","content":"Not typically required. Instead, focus on clean resume, CPA progress, and Excel/modeling skills. Internship at Big 4 (Deloitte, KPMG, PwC, EY) is a major credential.","priority":3},{"category":"market","content":"Steady demand in audit firms, corporate finance, and SMEs. However, entry-level bookkeeping roles are being automated. Advisory and forensic accounting are growing.","priority":1},{"category":"timeline","content":"4-year degree + CPA exam (1-2 years) → Junior Accountant (2-3 years) → Senior (3-5 years). Manager level typically requires 6-8 years and CPA.","priority":2},{"category":"salary","content":"Entry: 20,000-30,000 THB. Mid-level: 35,000-55,000 THB. Senior/CPA: 60,000-100,000+ THB. Big 4 starting salaries are 25,000-35,000 THB but accelerate quickly.","priority":1},{"category":"competition","content":"High competition for Big 4 and MNC roles. Many accounting graduates each year. CPA license and English fluency are the main differentiators.","priority":2}]'::jsonb
  ),
  (
    'customer-service-representative',
    ARRAY['support agent', 'call center agent', 'help desk', 'customer support'],
    'exposed',
    'Conversational AI and large language models now handle tier-1 inquiries such as refunds, password resets, and order tracking with high accuracy. Companies are deploying AI agents 24/7, reducing headcount for routine support while reserving humans for escalations.',
    '[{"title":"Occupational Outlook Handbook: Customer Service Representatives","url":"https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"The State of AI in Customer Service","url":"https://www.mckinsey.com/capabilities/growth-marketing-and-sales/our-insights/the-state-of-ai-in-customer-service","author":"McKinsey & Company","date":"2023-10-20"},{"title":"รายงานเงินเดือน Customer Service ประจำปี 2024","url":"https://www.jobthai.com/salary-report/customer-service","author":"JobThai","date":"2024-12-01"},{"title":"Thailand Call Center Industry Report 2024","url":"https://www.depa.or.th/th/article/call-center-industry","author":"สำนักงานส่งเสริมเศรษฐกิจดิจิทัล (DEPA)","date":"2024-02-01"},{"title":"Thailand BPO Market Outlook 2024","url":"https://www.boi.go.th/th/investment-opportunities/bpo","author":"สำนักงานคณะกรรมการส่งเสริมการลงทุน (BOI)","date":"2024-01-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Communication, empathy, problem-solving, CRM software (Zendesk, Salesforce), and basic technical troubleshooting. AI chatbot management is an emerging skill.","priority":1},{"category":"education","content":"No specific degree required. Any bachelor degree is acceptable. Some roles prefer Arts, Communication, or Business graduates.","priority":3},{"category":"certifications","content":"Not typically required. Some companies value customer service certifications (e.g., Zendesk Certified).","priority":4},{"category":"portfolio","content":"Not applicable. Focus on communication skills, language proficiency, and any experience handling difficult situations.","priority":5},{"category":"market","content":"Declining for basic tier-1 support due to AI chatbots. Growing for technical support, VIP customer success, and bilingual roles (Thai-English, Thai-Japanese). BPO sector in Thailand is stable.","priority":1},{"category":"timeline","content":"Entry-level immediately after graduation. Senior/Team Lead in 2-3 years. Transition to Customer Success or Operations is common.","priority":2},{"category":"salary","content":"Entry: 18,000-25,000 THB. Mid-level: 28,000-40,000 THB. Senior/Team Lead: 45,000-60,000 THB. Bilingual roles (Japanese, Chinese) pay 30-50% more.","priority":1},{"category":"competition","content":"High competition for entry-level roles. Low barrier to entry. Differentiate with language skills, technical knowledge, or transition to customer success/sales roles.","priority":2}]'::jsonb
  ),
  (
    'translator',
    ARRAY['interpreter', 'linguist', 'localizer', 'translator-interpreter'],
    'exposed',
    'Neural machine translation has reached near-human quality for major language pairs, and real-time speech translation is now consumer-grade. Literary and legal translation still require cultural nuance, but general commercial translation demand is shrinking.',
    '[{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"How AI Is Changing Translation","url":"https://www.nature.com/articles/d41586-023-00437-2","author":"Nature","date":"2023-02-15"},{"title":"รายงานเงินเดือน Translator ประจำปี 2024","url":"https://www.jobthai.com/salary-report/translator","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะอักษรศาสตร์ สาขาภาษาอังกฤษ/ภาษาจีน/ภาษาญี่ปุ่น","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Language Services Market 2024","url":"https://www.depa.or.th/th/article/language-services","author":"สำนักงานส่งเสริมเศรษฐกิจดิจิทัล (DEPA)","date":"2024-03-01"}]'::jsonb,
    'content-writer',
    '[{"category":"skills","content":"Native-level fluency in at least 2 languages, cultural nuance, CAT tools (Trados, MemoQ), and AI post-editing. Specialization (legal, medical, technical) is essential.","priority":1},{"category":"education","content":"Languages, Linguistics, or Translation at Chulalongkorn, Thammasat, or Silpakorn. Some roles accept unrelated degrees with proven language proficiency.","priority":2},{"category":"certifications","content":"ATA certification (US), JLPT N1 (Japanese), HSK 6 (Chinese), or DALF C2 (French). Thai translation associations also offer certifications.","priority":2},{"category":"portfolio","content":"Translation samples in your specialization. A small website or LinkedIn portfolio with 5-10 sample translations. Confidentiality agreements may limit what you can share.","priority":2},{"category":"market","content":"General translation is shrinking due to AI. Legal, medical, and certified translation remain stable. Japanese-Thai and Chinese-Thai pairs are in highest demand.","priority":1},{"category":"timeline","content":"4-year degree + specialization building. Freelance work can start immediately. Full-time agency roles: 1-2 years junior → mid-level.","priority":2},{"category":"salary","content":"Entry: 20,000-30,000 THB. Mid-level: 35,000-50,000 THB. Senior/Specialized: 60,000-90,000+ THB. Freelance: 200-800 THB per 100 words depending on language pair and specialization.","priority":1},{"category":"competition","content":"Very high competition for general translation. Niche specialization and rare language pairs (Japanese, Korean, Chinese) are the only viable paths forward.","priority":2}]'::jsonb
  ),
  (
    'paralegal',
    ARRAY['legal assistant', 'legal secretary', 'law clerk'],
    'exposed',
    'AI contract analysis, e-discovery platforms, and document-review tools can process thousands of pages in hours. Paralegals who specialize in routine discovery, due diligence, and form drafting face displacement, though litigation support and client interaction roles are more durable.',
    '[{"title":"Occupational Outlook Handbook: Paralegals and Legal Assistants","url":"https://www.bls.gov/ooh/legal/paralegals-and-legal-assistants.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"AI and the Legal Profession","url":"https://www.mckinsey.com/industries/public-sector/our-insights/ai-and-the-legal-profession","author":"McKinsey & Company","date":"2023-09-10"},{"title":"รายงานเงินเดือน Paralegal ประจำปี 2024","url":"https://www.jobthai.com/salary-report/paralegal","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะนิติศาสตร์ จุฬาฯ/ธรรมศาสตร์","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Legal Tech Adoption Report 2024","url":"https://www.lawyerscouncil.or.th/","author":"สภาทนายความ","date":"2024-01-01"}]'::jsonb,
    'lawyer',
    '[{"category":"skills","content":"Legal research, document drafting, case management, e-discovery tools, and attention to detail. Tech-savvy paralegals who can manage AI tools are more resilient.","priority":1},{"category":"education","content":"Law (LL.B.) or Paralegal Studies at Chulalongkorn, Thammasat, or Ramkhamhaeng. Some roles accept any bachelor degree with legal training.","priority":1},{"category":"certifications","content":"Not formally required in Thailand, but legal research certifications and e-discovery training (e.g., Relativity) add value.","priority":3},{"category":"portfolio","content":"Not applicable. Focus on legal writing samples, research skills, and any internship experience at law firms or corporate legal departments.","priority":4},{"category":"market","content":"Declining for routine document review due to AI. Stable for litigation support, corporate M&A, and client-facing roles. International law firms in Bangkok still hire actively.","priority":1},{"category":"timeline","content":"4-year law degree + bar exam (for lawyer track). Paralegal roles: entry immediately after graduation. Senior paralegal in 3-5 years.","priority":2},{"category":"salary","content":"Entry: 22,000-32,000 THB. Mid-level: 35,000-50,000 THB. Senior: 55,000-80,000 THB. International firms pay 50-100% more than Thai firms.","priority":1},{"category":"competition","content":"High competition. Many law graduates compete for limited paralegal roles. Strongest candidates transition to lawyer training contracts or specialize in high-demand areas (corporate, IP).","priority":2}]'::jsonb
  ),
  (
    'teacher',
    ARRAY['educator', 'instructor', 'school teacher', 'classroom teacher'],
    'growing',
    'Despite AI tutoring tools, the social-emotional, mentorship, and classroom-management aspects of teaching remain irreplaceable. Global teacher shortages are acute in STEM and special education. The U.S. alone needs an estimated 200,000 additional teachers annually.',
    '[{"title":"Occupational Outlook Handbook: High School Teachers","url":"https://www.bls.gov/ooh/education-training-and-library/high-school-teachers.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"รายงานเงินเดือน Teacher ประจำปี 2024","url":"https://www.jobthai.com/salary-report/teacher","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะครุศาสตร์ จุฬาฯ/ธรรมศาสตร์/มหิดล","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Teacher Shortage Report 2024","url":"https://www.obec.go.th/","author":"สำนักงานคณะกรรมการการศึกษาขั้นพื้นฐาน (สพฐ.)","date":"2024-01-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Subject expertise, classroom management, pedagogy, empathy, and technology integration (Google Classroom, LMS). English fluency is highly valued for international schools.","priority":1},{"category":"education","content":"Education degree (ครุศาสตร์) at Chulalongkorn, Thammasat, or Srinakharinwirot. International schools often prefer degrees from Western universities.","priority":1},{"category":"certifications","content":"Thai teaching license (ใบประกอบวิชาชีพครู) is required for public schools. TEFL/TESOL for English teaching. International schools value PGCE or equivalent.","priority":1},{"category":"portfolio","content":"Teaching practicum reports, lesson plans, and any tutoring or teaching assistant experience. Video lessons or educational content on YouTube/TikTok are a plus.","priority":3},{"category":"market","content":"Chronic shortage in Thai public schools, especially for math, science, and English. International schools in Bangkok are expanding. Private tutoring market is huge.","priority":1},{"category":"timeline","content":"5-year education degree (including practicum) → licensed teacher. Career progression: teacher → head of department → vice principal → principal (10-15 years).","priority":2},{"category":"salary","content":"Public school: 25,000-40,000 THB (with regular government increases). International school: 60,000-150,000+ THB. Private tutoring: 500-2,000 THB/hour.","priority":1},{"category":"competition","content":"Moderate for public schools (shortage helps). Very competitive for top international schools (require advanced degrees and experience). English teachers are in highest demand.","priority":2}]'::jsonb
  ),
  (
    'nurse',
    ARRAY['registered nurse', 'rn', 'healthcare nurse', 'clinical nurse'],
    'growing',
    'Aging populations in developed and emerging economies are driving unprecedented demand for nurses. The work requires physical dexterity, emotional intelligence, and split-second clinical judgment in unpredictable environments. The WHO projects a global shortage of 10 million nurses by 2030.',
    '[{"title":"Occupational Outlook Handbook: Registered Nurses","url":"https://www.bls.gov/ooh/healthcare/registered-nurses.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"State of the Worlds Nursing 2023","url":"https://www.who.int/publications/i/item/9789240069947","author":"World Health Organization","date":"2023-01-01"},{"title":"รายงานเงินเดือน Nurse ประจำปี 2024","url":"https://www.jobthai.com/salary-report/nurse","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะพยาบาลศาสตร์ มหิดล/จุฬาฯ/มข.","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Nursing Workforce Strategy 2024","url":"https://www.moph.go.th/","author":"กระทรวงสาธารณสุข","date":"2024-01-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Clinical skills, patient care, medical documentation, emergency response, and empathy. Specialized skills (ICU, OR, pediatric) increase earning potential significantly.","priority":1},{"category":"education","content":"Nursing Science (พยาบาลศาสตร์) at Mahidol, Chulalongkorn, or Khon Kaen University. 4-year bachelor degree is now standard for hospital employment.","priority":1},{"category":"certifications","content":"Thai Nursing License (ใบประกอบวิชาชีพพยาบาล) is mandatory. ACLS, BLS, and specialized certifications (wound care, dialysis) increase salary.","priority":1},{"category":"portfolio","content":"Not applicable. Clinical practicum hours (1,000+) and hospital rotation experience are the key credentials.","priority":4},{"category":"market","content":"Severe shortage in Thailand, especially in rural areas. Private hospitals (Bumrungrad, Samitivej, Bangkok Hospital) offer the best salaries. Overseas opportunities (Saudi, Singapore, UK) are popular.","priority":1},{"category":"timeline","content":"4-year nursing degree + licensing exam → staff nurse (1-2 years) → senior nurse (3-5 years) → head nurse (5-8 years). Specialization accelerates advancement.","priority":2},{"category":"salary","content":"Public hospital: 25,000-40,000 THB. Private hospital: 35,000-60,000 THB. Specialized/head nurse: 60,000-100,000+ THB. Overseas contracts: 100,000-200,000+ THB.","priority":1},{"category":"competition","content":"Low competition due to shortage. However, top private hospitals are selective. English fluency and specialized skills are key differentiators.","priority":3}]'::jsonb
  ),
  (
    'electrician',
    ARRAY['electrical technician', 'wireman', 'electrical contractor'],
    'growing',
    'Electrical infrastructure for renewable energy, data centers, and electric vehicles is expanding rapidly. The trade requires on-site problem solving, physical installation, and safety certification that cannot be automated. BLS projects steady growth and strong median wages.',
    '[{"title":"Occupational Outlook Handbook: Electricians","url":"https://www.bls.gov/ooh/construction-and-extraction/electricians.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"รายงานเงินเดือน Electrician ประจำปี 2024","url":"https://www.jobthai.com/salary-report/electrician","author":"JobThai","date":"2024-12-01"},{"title":"Thailand Electrical Licensing Requirements","url":"https://www.diw.go.th/","author":"กรมโรงงานอุตสาหกรรม","date":"2024-01-01"},{"title":"Thailand Renewable Energy Investment 2024","url":"https://www.boi.go.th/th/investment-opportunities/renewable-energy","author":"สำนักงานคณะกรรมการส่งเสริมการลงทุน (BOI)","date":"2024-01-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Electrical wiring, circuit troubleshooting, blueprint reading, safety compliance, and renewable energy installation (solar, EV charging). PLC programming is a premium skill.","priority":1},{"category":"education","content":"Electrical Engineering Technology at KMUTT, Rajamangala, or vocational colleges (ปวส.). Apprenticeship under a licensed electrician is the traditional path.","priority":1},{"category":"certifications","content":"Electrical License (ใบประกอบวิชาชีพไฟฟ้า) from the Department of Energy. Solar PV installation certification is increasingly valuable.","priority":1},{"category":"portfolio","content":"Not applicable. Work experience, apprenticeship completion, and safety record are the key credentials. Photos of completed installations can help for independent contracting.","priority":4},{"category":"market","content":"High demand for solar installation, EV charging infrastructure, and industrial maintenance. Thailand''s renewable energy push is creating thousands of new electrical jobs.","priority":1},{"category":"timeline","content":"Vocational training (2 years) or apprenticeship (3-4 years) → licensed electrician. Senior/contractor roles in 5-8 years. Specialization (solar, industrial) accelerates earnings.","priority":2},{"category":"salary","content":"Entry: 20,000-30,000 THB. Mid-level: 35,000-55,000 THB. Senior/Contractor: 60,000-100,000+ THB. Independent contractors can earn 150,000+ THB on large projects.","priority":1},{"category":"competition","content":"Low competition. Skilled electricians are in shortage. Licensed electricians with solar/EV skills are especially scarce and command premium rates.","priority":3}]'::jsonb
  ),
  (
    'truck-driver',
    ARRAY['long-haul driver', 'delivery driver', 'freight driver', 'cdl driver'],
    'shifting',
    'Autonomous trucking technology is advancing, but regulatory, liability, and edge-case safety barriers mean full driverless deployment is still years away. In the near term, drivers are shifting to last-mile delivery, fleet supervision, and human-in-the-loop monitoring roles.',
    '[{"title":"Occupational Outlook Handbook: Heavy and Tractor-Trailer Truck Drivers","url":"https://www.bls.gov/ooh/transportation-and-material-moving/heavy-and-tractor-trailer-truck-drivers.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"Autonomous Trucks and the Future of Freight","url":"https://www.mckinsey.com/industries/travel-logistics-and-infrastructure/our-insights/autonomous-trucks-and-the-future-of-freight","author":"McKinsey & Company","date":"2023-07-20"},{"title":"รายงานเงินเดือน Truck Driver ประจำปี 2024","url":"https://www.jobthai.com/salary-report/truck-driver","author":"JobThai","date":"2024-12-01"},{"title":"Thailand Logistics Industry Outlook 2024","url":"https://www.boi.go.th/th/investment-opportunities/logistics","author":"สำนักงานคณะกรรมการส่งเสริมการลงทุน (BOI)","date":"2024-01-01"},{"title":"Thailand Transport Licensing Requirements","url":"https://www.dlt.go.th/","author":"กรมการขนส่งทางบก","date":"2024-01-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Vehicle operation, route planning, basic vehicle maintenance, GPS/navigation systems, and logistics software. Fleet management and last-mile optimization skills are emerging.","priority":1},{"category":"education","content":"No degree required. Vocational driving license (ท.2, ท.3, ท.4) from Department of Land Transport. High school diploma is preferred by some employers.","priority":2},{"category":"certifications","content":"Commercial Driver''s License (ใบขับขี่รถบรรทุก) is mandatory. Hazardous materials certification increases pay. Defensive driving courses are valued.","priority":1},{"category":"portfolio","content":"Not applicable. Clean driving record, accident history, and employer references are the key credentials.","priority":4},{"category":"market","content":"Stable demand in logistics, e-commerce delivery (Shopee, Lazada, Flash Express), and construction. Long-haul faces future disruption from automation. Last-mile delivery is growing.","priority":1},{"category":"timeline","content":"License acquisition (1-3 months) → entry driver immediately. Senior/long-haul roles in 2-3 years. Fleet supervisor in 5-7 years.","priority":2},{"category":"salary","content":"Entry: 18,000-25,000 THB. Mid-level: 28,000-40,000 THB. Long-haul/specialized: 45,000-70,000 THB. E-commerce delivery (own vehicle): 30,000-60,000+ THB depending on volume.","priority":1},{"category":"competition","content":"Low competition. Driver shortage is chronic in Thailand. However, long-haul roles face uncertain future. Transition to logistics coordination or fleet management is advisable.","priority":2}]'::jsonb
  ),
  (
    'journalist',
    ARRAY['reporter', 'news writer', 'correspondent', 'investigative journalist'],
    'shifting',
    'AI can generate earnings summaries and sports recaps, but investigative journalism, on-the-ground reporting, and accountability storytelling require human judgment, source relationships, and ethical reasoning. The industry is contracting in some areas while premium investigative outlets see stable or growing support.',
    '[{"title":"Occupational Outlook Handbook: News Analysts, Reporters, and Journalists","url":"https://www.bls.gov/ooh/media-and-communication/news-analysts-reporters-and-journalists.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"Journalism and AI","url":"https://reutersinstitute.politics.ox.ac.uk/journalism-and-ai","author":"Reuters Institute","date":"2023-11-01"},{"title":"รายงานเงินเดือน Journalist ประจำปี 2024","url":"https://www.jobthai.com/salary-report/journalist","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะนิเทศศาสตร์ จุฬาฯ/ธรรมศาสตร์/มหิดล","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Media Landscape Report 2024","url":"https://www.nbt.or.th/","author":"สำนักงานกรมประชาสัมพันธ์","date":"2024-01-01"}]'::jsonb,
    'content-writer',
    '[{"category":"skills","content":"Research, interviewing, writing, fact-checking, multimedia storytelling, and social media. Data journalism and video production skills are increasingly important.","priority":1},{"category":"education","content":"Journalism, Communication Arts, or Political Science at Chulalongkorn, Thammasat, or Mahidol. Some successful journalists have degrees in their beat (economics, law, science).","priority":2},{"category":"certifications","content":"Not formally required. Data journalism workshops (Thai Journalists Association) and multimedia training are helpful.","priority":4},{"category":"portfolio","content":"Published articles, clips, or a personal website with 10+ pieces. Include investigative work, multimedia stories, and any awards. Social media following is a plus.","priority":1},{"category":"market","content":"Traditional print/TV journalism is declining. Digital-native outlets (The Standard, The Matter, Khaosod English) are growing. Freelance and Substack-style independent journalism is emerging.","priority":1},{"category":"timeline","content":"4-year degree + internship at newsroom → junior reporter (1-2 years) → reporter (3-5 years) → senior/editor (5-10 years). Many pivot to PR, content, or communications.","priority":2},{"category":"salary","content":"Entry: 20,000-30,000 THB. Mid-level: 35,000-55,000 THB. Senior/Editor: 60,000-100,000+ THB. Freelance: 2,000-10,000 THB per article. Independent journalism income is highly variable.","priority":1},{"category":"competition","content":"Very high competition for staff positions at major outlets. Digital multimedia skills and niche expertise (business, tech, environment) are key differentiators. English fluency opens international opportunities.","priority":2}]'::jsonb
  ),
  (
    'financial-analyst',
    ARRAY['investment analyst', 'equity analyst', 'research analyst', 'securities analyst'],
    'shifting',
    'Algorithmic trading and AI-powered financial modeling have automated quantitative analysis, but strategic advisory, client relationships, and narrative-driven investment theses still require human expertise. Analysts are shifting from spreadsheet modeling to data interpretation and stakeholder communication.',
    '[{"title":"Occupational Outlook Handbook: Financial Analysts","url":"https://www.bls.gov/ooh/business-and-financial/financial-analysts.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"รายงานเงินเดือน Financial Analyst ประจำปี 2024","url":"https://www.jobthai.com/salary-report/financial-analyst","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะบัญชี/เศรษฐศาสตร์/บริหารธุรกิจ จุฬาฯ","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Capital Market Outlook 2024","url":"https://www.set.or.th/","author":"ตลาดหลักทรัพย์แห่งประเทศไทย","date":"2024-01-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Financial modeling (Excel, Python), valuation, accounting, data analysis, and presentation. CFA curriculum knowledge is expected even before passing exams.","priority":1},{"category":"education","content":"Finance, Accounting, or Economics at Chulalongkorn, Thammasat, or Mahidol. MBA or Master in Finance is increasingly common for senior roles.","priority":1},{"category":"certifications","content":"CFA (Chartered Financial Analyst) is the gold standard. CPA, FRM, or CFP are also valued depending on the specialization.","priority":1},{"category":"portfolio","content":"Investment research reports, stock pitch decks, and financial models. A personal blog or Substack analyzing Thai stocks is a strong differentiator.","priority":2},{"category":"market","content":"Strong demand in investment banking, asset management, and corporate finance. Thai capital markets are growing. ESG analysis is an emerging specialty.","priority":1},{"category":"timeline","content":"4-year degree + 2-3 years as Analyst → Senior Analyst (3-5 years) → Associate/VP (5-8 years). CFA Level 1-3 typically takes 2-4 years alongside work.","priority":2},{"category":"salary","content":"Entry: 30,000-45,000 THB. Mid-level: 60,000-100,000 THB. Senior/Investment Banking: 150,000-500,000+ THB. Bonuses can equal 50-200% of base salary.","priority":1},{"category":"competition","content":"Very competitive for investment banking and top asset managers. CFA progress, target university background, and internship experience at financial institutions are essential.","priority":2}]'::jsonb
  ),
  (
    'hr-recruiter',
    ARRAY['talent acquisition specialist', 'recruiter', 'hiring manager', 'sourcer'],
    'shifting',
    'AI resume screening and chatbot scheduling have automated high-volume sourcing, but culture fit assessment, executive search, and candidate experience design remain deeply human. Recruiters are pivoting toward employer branding, talent strategy, and DEI consulting.',
    '[{"title":"Occupational Outlook Handbook: Human Resources Specialists","url":"https://www.bls.gov/ooh/business-and-financial/human-resources-specialists.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"รายงานเงินเดือน HR Recruiter ประจำปี 2024","url":"https://www.jobthai.com/salary-report/hr-recruiter","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะบริหารธุรกิจ สาขาการจัดการ/การบัญชี","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand HR Tech Adoption Report 2024","url":"https://www.depa.or.th/th/article/hr-tech-adoption","author":"สำนักงานส่งเสริมเศรษฐกิจดิจิทัล (DEPA)","date":"2024-03-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Sourcing, interviewing, employer branding, ATS/HRIS systems, data analysis, and relationship building. LinkedIn Recruiter and AI sourcing tools are now standard.","priority":1},{"category":"education","content":"Human Resources, Business Administration, or Psychology at Chulalongkorn, Thammasat, or Assumption University. Any business degree is acceptable with HR experience.","priority":2},{"category":"certifications","content":"SPHR, PHR, or Thai HR certifications (สมาคมการบริหารงานบุคคลแห่งประเทศไทย). LinkedIn Recruiter certification is practical.","priority":3},{"category":"portfolio","content":"Not typical. Instead, track metrics: time-to-fill, offer acceptance rate, candidate satisfaction. Case studies of difficult searches are impressive in interviews.","priority":3},{"category":"market","content":"Steady demand across all industries. Tech startups and MNCs are most active. Executive search (headhunting) pays the best. HR tech is automating junior sourcing roles.","priority":1},{"category":"timeline","content":"4-year degree + 1-2 years as HR Coordinator → Recruiter (2-3 years) → Senior/TA Manager (5-7 years). Executive search requires 5+ years of network building.","priority":2},{"category":"salary","content":"Entry: 22,000-35,000 THB. Mid-level: 40,000-65,000 THB. Senior/TA Manager: 80,000-150,000+ THB. Executive search consultants can earn 200,000+ THB with commission.","priority":1},{"category":"competition","content":"Moderate competition. Many HR generalists transition to recruiting. Strong LinkedIn network, industry specialization, and English fluency are differentiators.","priority":2}]'::jsonb
  ),
  (
    'photographer',
    ARRAY['photojournalist', 'event photographer', 'portrait photographer', 'commercial photographer'],
    'shifting',
    'Generative AI can synthesize stock imagery, but event photography, photojournalism, and brand storytelling demand real-world presence, timing, and human connection. The market is polarizing: commodity stock photography is declining, while live and documentary photography persists.',
    '[{"title":"Occupational Outlook Handbook: Photographers","url":"https://www.bls.gov/ooh/media-and-communication/photographers.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"The Future of Jobs Report 2023","url":"https://www.weforum.org/reports/the-future-of-jobs-report-2023/","author":"World Economic Forum","date":"2023-04-30"},{"title":"รายงานเงินเดือน Photographer ประจำปี 2024","url":"https://www.jobthai.com/salary-report/photographer","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะสถาปัตยกรรมศาสตร์ สาขาออกแบบนิเทศศาสตร์","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Creative Industry Outlook 2024","url":"https://www.creative-economy.or.th/report-2024","author":"สำนักงานเศรษฐกิจสร้างสรรค์","date":"2024-03-01"}]'::jsonb,
    'graphic-designer',
    '[{"category":"skills","content":"Camera operation, lighting, composition, photo editing (Lightroom, Photoshop), and business management. Drone photography and video are high-demand add-ons.","priority":1},{"category":"education","content":"Photography, Visual Arts, or Communication Arts at Silpakorn, Bangkok University, or Chulalongkorn. Many successful photographers are self-taught.","priority":3},{"category":"certifications","content":"Not required. Some value WPA or PPA certifications. Drone pilot license (from Department of Land Transport) is needed for commercial drone work.","priority":3},{"category":"portfolio","content":"Strong online portfolio (Instagram, personal website) with 20-50 curated images per specialization. Before/after editing examples impress clients.","priority":1},{"category":"market","content":"Event photography (weddings, corporate) is stable. Commercial/product photography for e-commerce is growing. Stock photography is declining due to AI. Social media content creation is a new revenue stream.","priority":1},{"category":"timeline","content":"No fixed timeline. Many start as assistants (1-2 years) before going independent. Building a client base takes 2-4 years. Specialization accelerates earnings.","priority":2},{"category":"salary","content":"Entry/Assistant: 18,000-25,000 THB. Mid-level freelance: 30,000-60,000 THB. Established commercial photographer: 80,000-200,000+ THB. Wedding photography: 20,000-100,000+ THB per event.","priority":1},{"category":"competition","content":"High competition, especially for event photography. Differentiate with specialization (food, architecture, fashion), video skills, or strong social media presence. AI image generation is disrupting stock photography.","priority":2}]'::jsonb
  ),
  (
    'lawyer',
    ARRAY['attorney', 'counsel', 'solicitor', 'barrister'],
    'growing',
    'Complex litigation, negotiation, and regulatory strategy require contextual reasoning, ethical judgment, and client advocacy that AI cannot replicate. While AI accelerates legal research and contract drafting, demand for lawyers in high-stakes disputes, M&A, and compliance continues to grow.',
    '[{"title":"Occupational Outlook Handbook: Lawyers","url":"https://www.bls.gov/ooh/legal/lawyers.htm","author":"U.S. Bureau of Labor Statistics","date":"2024-01-01"},{"title":"AI and the Legal Profession","url":"https://www.mckinsey.com/industries/public-sector/our-insights/ai-and-the-legal-profession","author":"McKinsey & Company","date":"2023-09-10"},{"title":"รายงานเงินเดือน Lawyer ประจำปี 2024","url":"https://www.jobthai.com/salary-report/lawyer","author":"JobThai","date":"2024-12-01"},{"title":"TCAS รอบที่ 3 : คณะนิติศาสตร์ จุฬาฯ/ธรรมศาสตร์/มหิดล","url":"https://www.admission.chula.ac.th/tcas","author":"สำนักงานรับสมัครและคัดเลือก จุฬาฯ","date":"2025-01-01"},{"title":"Thailand Legal Services Market 2024","url":"https://www.lawyerscouncil.or.th/","author":"สภาทนายความ","date":"2024-01-01"}]'::jsonb,
    NULL,
    '[{"category":"skills","content":"Legal research, drafting, negotiation, oral advocacy, case strategy, and client management. Tech literacy (legal tech, contract automation) is increasingly important.","priority":1},{"category":"education","content":"Law (นิติศาสตร์) at Chulalongkorn, Thammasat, or Ramkhamhaeng. LL.B. is required for the Thai Bar Exam. Some pursue LL.M. overseas for international firms.","priority":1},{"category":"certifications","content":"Thai Bar Association membership (สภาทนายความ) is mandatory for court practice. Foreign lawyer licenses (for international firms) require additional qualifications.","priority":1},{"category":"portfolio","content":"Not applicable. Moot court experience, law review, and published articles are valued. Internship at top-tier firms (Baker McKenzie, Tilleke & Gibbins) is a major credential.","priority":2},{"category":"market","content":"Strong demand in corporate law, M&A, IP, and dispute resolution. International firms in Bangkok are expanding. Thai companies going regional need more legal support.","priority":1},{"category":"timeline","content":"4-year LL.B. + Thai Bar Exam (1 year) → trainee lawyer (1-2 years) → associate (3-5 years) → senior associate (5-8 years) → partner (8-15 years).","priority":2},{"category":"salary","content":"Entry/Trainee: 25,000-40,000 THB. Associate: 45,000-80,000 THB. Senior/International firm: 100,000-300,000+ THB. Partners at top firms: 500,000-2,000,000+ THB.","priority":1},{"category":"competition","content":"Very competitive for top-tier firms and international offices. Many law graduates each year. Bar exam pass, target university, and internship pedigree are the main filters.","priority":2}]'::jsonb
  )
ON CONFLICT (slug) DO UPDATE SET
  aliases = EXCLUDED.aliases,
  sources = EXCLUDED.sources,
  insights = EXCLUDED.insights;
