-- Add AI impact, specialty tracks, and future opportunities to career_survival
-- Idempotent: updates existing rows by slug
-- Keeps tier, reasoning, sources, insights, and escape_route_slug unchanged

ALTER TABLE public.career_survival
ADD COLUMN IF NOT EXISTS ai_impact jsonb DEFAULT NULL,
ADD COLUMN IF NOT EXISTS specialty_tracks jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS future_opportunities jsonb DEFAULT '[]'::jsonb;

COMMENT ON COLUMN public.career_survival.ai_impact IS 'Object: automation_risk (1-10), tools_to_master (string[]), augmented_tasks (string), automated_tasks (string)';
COMMENT ON COLUMN public.career_survival.specialty_tracks IS 'Array of objects: {name, description, demand_level (high/medium/low), salary_premium (string)}';
COMMENT ON COLUMN public.career_survival.future_opportunities IS 'Array of objects: {role, description, timeline (years), transition_difficulty (easy/medium/hard)}';

UPDATE public.career_survival SET
  tier = 'growing',
  reasoning = 'Software engineering is still a strong career, but the easy version is becoming weaker. AI automates routine coding, boilerplate apps, simple scripts, and basic debugging. The safest engineers are those who understand systems, users, product tradeoffs, security, and how to use AI tools to ship faster. The entry-level bar is rising: generic juniors face more competition, while AI-native builders with real problem-solving ability are in high demand.',
  ai_impact = '{"automation_risk":4,"junior_risk":6,"senior_risk":2,"tools_to_master":["Claude Code","Cursor","GitHub Copilot","v0.dev","ChatGPT API","GitHub Actions","Docker","Supabase","AWS/GCP basics"],"augmented_tasks":"Boilerplate coding, debugging, documentation, test generation, code review assistance, UI prototyping. Engineers now focus on system architecture, product judgment, and complex problem-solving rather than syntax memorization.","automated_tasks":"Simple CRUD apps, basic HTML/CSS layouts, small scripts, repetitive refactoring, standard API endpoints. Generic copy-paste coding and stack-overflow-driven development are being replaced by AI pair programming."}'::jsonb,
  specialty_tracks = '[{"name":"Backend Engineer","description":"Build APIs, databases, and distributed systems. The backbone of every tech company. Most common entry path.","demand_level":"high","pay_upside":"Medium-high"},{"name":"AI/ML Engineer","description":"Design ML models, fine-tune LLMs, build AI-powered features. Requires strong math and coding.","demand_level":"high","pay_upside":"High"},{"name":"DevOps / Platform Engineer","description":"Manage CI/CD, cloud infrastructure, and developer tooling. Critical for scaling teams.","demand_level":"high","pay_upside":"High"},{"name":"Mobile Engineer","description":"Build iOS/Android apps using React Native, Flutter, or Swift. Steady demand.","demand_level":"medium","pay_upside":"Medium"},{"name":"Security Engineer","description":"Design secure architectures and perform penetration testing. Growing with cyber threats.","demand_level":"high","pay_upside":"High"},{"name":"AI Product Engineer","description":"Build AI-native products from scratch. Combines engineering with product intuition and AI fluency.","demand_level":"high","pay_upside":"High"}]'::jsonb,
  future_opportunities = '[{"role":"AI Product Engineer","description":"Build AI-native products. Requires engineering + product + AI fluency. Building demos is easy; building useful products is hard.","timeline":"2-4 years","transition_difficulty":"medium"},{"role":"Backend / Platform Engineer","description":"Deep specialization in scalable systems. Natural progression from general backend work.","timeline":"3-5 years","transition_difficulty":"medium"},{"role":"AI Systems Architect","description":"Design how AI integrates into products at scale. Requires deep understanding of both engineering and ML infrastructure.","timeline":"5-7 years","transition_difficulty":"hard"},{"role":"Engineering Manager / CTO","description":"Lead engineering teams and technical strategy. Natural progression for senior engineers who enjoy mentorship.","timeline":"7-10 years","transition_difficulty":"hard"},{"role":"Technical Founder","description":"Start your own SaaS or AI tool company. Thailand startup ecosystem is growing with DEPA support. Can start earlier, but succeeding is very hard.","timeline":"3-10 years","transition_difficulty":"very hard"}]'::jsonb,
  insights = '[{"category":"skills","content":"Core: Python, JavaScript/TypeScript, SQL, Git, APIs, data structures, debugging, testing. Advanced: Docker, cloud fundamentals, system design, security basics, AI tool use, product thinking. The bar is rising: you need to understand what AI generates, not just copy it.","priority":1},{"category":"education","content":"Computer Engineering, Computer Science, or Software Engineering at Chulalongkorn, Kasetsart, KMUTT, Mahidol, KMITL, or Thammasat. Portfolio รอบ 1 is useful for students with strong projects. Admission รอบ 3 is the broader academic route.","priority":1},{"category":"market","content":"Thailand: fintech (SCB, KBANK, LINE BK), e-commerce (Shopee, Lazada), travel/tech (Agoda), logistics/startups (Flash Express), software houses, AI startups, enterprise IT teams. Global: remote work possible for strong English + portfolio. Not everyone gets Agoda/LINE/Shopee — many paths exist.","priority":1},{"category":"salary","content":"Thailand typical: Entry 25k-45k THB/month, Mid 50k-90k, Senior 90k-160k. Top Bangkok/international: Entry 40k-70k, Mid 80k-130k, Senior 150k-250k+. Pay varies heavily by English, portfolio, company type, and interview skill.","priority":1},{"category":"competition","content":"Very competitive for top tech companies and international firms. Moderate for SMEs and startups. The entry-level bar is rising: generic coding is commoditized. Strong portfolio, English fluency, and AI-native problem-solving are key differentiators.","priority":2},{"category":"portfolio","content":"GitHub with 3+ production-grade projects (full-stack web app, mobile app, or API). Use AI tools, but understand every line. Contributions to open source are a strong differentiator. Build something real, not just tutorial projects.","priority":2},{"category":"certifications","content":"AWS Certified Developer, Google Associate Cloud Engineer, or Azure Fundamentals. Less critical than a strong portfolio, but Thai companies increasingly value cloud certs for senior roles.","priority":3},{"category":"timeline","content":"4-year degree + 1-2 years junior experience → mid-level. Senior roles typically require 4-6 years. The path is flexible: some skip degree via bootcamps + strong portfolio, but this is harder in Thailand.","priority":2}]'::jsonb
WHERE slug = 'software-engineer';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":4,"tools_to_master":["ChatGPT API","Claude","Jupyter AI","GitHub Copilot","H2O.ai","DataRobot","Tableau GPT","Hex"],"augmented_tasks":"AI accelerates data cleaning, exploratory analysis, feature engineering, and visualization. Data scientists now spend more time on problem framing, experimental design, and communicating insights to stakeholders. AutoML handles baseline model selection.","automated_tasks":"Routine data preprocessing, simple EDA reports, basic model benchmarking, and dashboard generation are increasingly automated. Junior data analysts who only run standard scikit-learn pipelines face displacement."}'::jsonb,
  specialty_tracks = '[{"name":"Machine Learning Engineer","description":"Productionize ML models at scale: MLOps, model serving, and monitoring. Bridges research and engineering.","demand_level":"high","salary_premium":"+40-60%"},{"name":"AI Research Scientist","description":"Push boundaries of AI research, publish papers, and develop novel architectures. Typically requires advanced degree.","demand_level":"high","salary_premium":"+60-100%"},{"name":"Business Intelligence Analyst","description":"Translate business questions into data answers. Focus on dashboards, KPIs, and strategic reporting.","demand_level":"medium","salary_premium":"same"},{"name":"NLP / LLM Specialist","description":"Work with Thai language models, fine-tune LLMs, and build conversational AI. Critical for Thai market AI.","demand_level":"high","salary_premium":"+50-70%"},{"name":"Data Engineer","description":"Build data pipelines, warehouses, and infrastructure. The foundation that enables all data science work.","demand_level":"high","salary_premium":"+30-40%"}]'::jsonb,
  future_opportunities = '[{"role":"Chief Data Officer","description":"Lead organization-wide data strategy and AI transformation. Requires business acumen plus technical depth.","timeline":"8-12 years","transition_difficulty":"hard"},{"role":"AI Product Manager","description":"Manage AI-powered products and features. Combines data science background with product management skills.","timeline":"5-7 years","transition_difficulty":"medium"},{"role":"Founder (AI SaaS)","description":"Build AI tools for Thai market needs: Thai NLP, local business analytics, or agricultural AI.","timeline":"5-10 years","transition_difficulty":"hard"},{"role":"Quantitative Researcher","description":"Work at hedge funds or prop trading firms applying ML to financial markets. Very high compensation.","timeline":"4-6 years","transition_difficulty":"medium"}]'::jsonb
WHERE slug = 'data-scientist';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":2,"tools_to_master":["ChatGPT","Claude","Notion AI","Figma AI","Amplitude","Mixpanel","Linear","Jira"],"augmented_tasks":"AI helps with user research synthesis, competitive analysis, writing PRDs, and generating user stories. PMs use AI to draft communications, analyze feedback at scale, and brainstorm feature ideas. Data analysis and A/B test interpretation are faster with AI assistants.","automated_tasks":"Basic roadmap templating, routine status reporting, and simple feature specification writing are partially automated. However, the strategic decisions, stakeholder alignment, and trade-off judgment remain deeply human."}'::jsonb,
  specialty_tracks = '[{"name":"Growth Product Manager","description":"Focus on acquisition, activation, retention, and revenue optimization. Data-driven and experiment-heavy.","demand_level":"high","salary_premium":"+30-50%"},{"name":"AI Product Manager","description":"Ship AI-powered features and manage LLM integrations. Requires understanding of model capabilities and limitations.","demand_level":"high","salary_premium":"+40-60%"},{"name":"Platform Product Manager","description":"Build internal tools, APIs, and infrastructure that other teams use. Technical depth required.","demand_level":"high","salary_premium":"+30-40%"},{"name":"B2B / Enterprise PM","description":"Manage complex sales cycles, enterprise features, and customer success integration.","demand_level":"medium","salary_premium":"+20-30%"}]'::jsonb,
  future_opportunities = '[{"role":"VP of Product / CPO","description":"Lead product strategy across multiple teams and business units. Natural progression for senior PMs.","timeline":"8-12 years","transition_difficulty":"medium"},{"role":"Founder / CEO","description":"Many successful founders were former PMs who understood user problems deeply. Thai startup ecosystem is supportive.","timeline":"5-10 years","transition_difficulty":"hard"},{"role":"Venture Capitalist","description":"Invest in startups using product judgment and market insight. Common path for PMs at successful companies.","timeline":"7-10 years","transition_difficulty":"medium"},{"role":"AI Strategy Consultant","description":"Advise companies on AI product strategy and digital transformation. Combines PM experience with AI fluency.","timeline":"5-7 years","transition_difficulty":"easy"}]'::jsonb
WHERE slug = 'product-manager';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":3,"tools_to_master":["Figma AI","Midjourney","ChatGPT","Claude","Maze","UserTesting AI","Galileo AI","Uizard"],"augmented_tasks":"AI generates UI variations, creates design system components, and produces user research summaries. Designers use AI for rapid prototyping, accessibility checks, and copy suggestions. Heatmap analysis and user behavior prediction are enhanced by AI tools.","automated_tasks":"Basic wireframe generation, color palette suggestions, and stock icon creation are increasingly automated. However, contextual inquiry, ethnographic research, and strategic design decisions require human empathy and judgment."}'::jsonb,
  specialty_tracks = '[{"name":"Product Designer","description":"Own end-to-end design from research to final UI. Most common and versatile UX track.","demand_level":"high","salary_premium":"+20-30%"},{"name":"UX Researcher","description":"Lead user research, usability testing, and synthesis. Critical for data-driven design decisions.","demand_level":"medium","salary_premium":"+15-25%"},{"name":"Design Systems Specialist","description":"Build and maintain scalable component libraries and design tokens. Essential for growing teams.","demand_level":"medium","salary_premium":"+20-30%"},{"name":"Interaction Designer","description":"Focus on micro-interactions, animations, and complex UI behaviors. Strong technical design skills.","demand_level":"medium","salary_premium":"+15-25%"},{"name":"Service Designer","description":"Design holistic experiences across touchpoints and organizational boundaries. Growing in enterprise.","demand_level":"medium","salary_premium":"+25-40%"}]'::jsonb,
  future_opportunities = '[{"role":"Design Director / VP of Design","description":"Lead design teams and establish design culture across the organization.","timeline":"7-10 years","transition_difficulty":"medium"},{"role":"AI Experience Designer","description":"Design interfaces for AI-powered products: chatbots, copilots, and generative AI tools. Emerging field.","timeline":"3-5 years","transition_difficulty":"easy"},{"role":"Founder (Design Tool / Agency)","description":"Start a design agency or build design tools for the Thai market.","timeline":"5-10 years","transition_difficulty":"hard"},{"role":"Product Manager","description":"Transition to PM using deep user understanding and product intuition. Common and natural path.","timeline":"4-6 years","transition_difficulty":"easy"}]'::jsonb
WHERE slug = 'ux-designer';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":7,"tools_to_master":["Midjourney","DALL-E 3","Stable Diffusion","Adobe Firefly","Runway ML","Canva Magic Studio","Krea","ComfyUI"],"augmented_tasks":"AI accelerates concept generation, mood board creation, asset variation, and background removal. Designers use AI for rapid iteration, style exploration, and resizing for multiple formats. Photoshop Generative Fill and Firefly streamline production workflows.","automated_tasks":"Stock photo creation, basic social media graphics, simple logo variations, and template-based designs are heavily automated. Clients increasingly expect AI-augmented speed for commodity design work."}'::jsonb,
  specialty_tracks = '[{"name":"Brand Identity Designer","description":"Create logos, brand systems, and visual guidelines. Requires deep strategic thinking beyond AI generation.","demand_level":"medium","salary_premium":"+20-30%"},{"name":"Motion Designer","description":"Animate graphics, create video content, and build interactive motion pieces. AI is less capable here.","demand_level":"high","salary_premium":"+40-60%"},{"name":"3D / AR Designer","description":"Build 3D assets, product visualizations, and AR experiences. Growing with metaverse and e-commerce.","demand_level":"high","salary_premium":"+50-70%"},{"name":"Creative Director","description":"Lead creative vision, art direction, and campaign strategy. The human judgment layer AI cannot replace.","demand_level":"medium","salary_premium":"+60-100%"}]'::jsonb,
  future_opportunities = '[{"role":"AI Creative Director","description":"Direct AI tools to produce campaigns at scale while maintaining brand consistency and creative vision.","timeline":"3-5 years","transition_difficulty":"easy"},{"role":"UX Designer","description":"Transition to UX using visual skills and adding research capabilities. Many graphic designers make this move successfully.","timeline":"2-4 years","transition_difficulty":"medium"},{"role":"Motion Designer / Video Director","description":"Pivot to video and motion where AI capabilities are weaker. Strong demand in Thai digital marketing.","timeline":"2-3 years","transition_difficulty":"easy"},{"role":"Founder (Creative Agency)","description":"Start a boutique agency specializing in AI-augmented creative production.","timeline":"5-8 years","transition_difficulty":"medium"}]'::jsonb
WHERE slug = 'graphic-designer';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":8,"tools_to_master":["ChatGPT","Claude","Jasper","Copy.ai","Grammarly","Hemingway Editor","Notion AI","Perplexity"],"augmented_tasks":"AI helps with ideation, outlining, first drafts, and SEO optimization. Writers use AI for research synthesis, grammar checking, and adapting tone for different audiences. Technical writers use AI to generate API documentation and code examples.","automated_tasks":"Routine blog posts, product descriptions, basic social media copy, and templated email sequences are increasingly automated. Generic SEO content farms are being replaced by AI. Low-value rewriting and summarization are commoditized."}'::jsonb,
  specialty_tracks = '[{"name":"Technical Writer","description":"Create documentation, API guides, and developer content. Requires deep technical understanding.","demand_level":"high","salary_premium":"+30-50%"},{"name":"Brand Storyteller","description":"Craft narrative-driven content for premium brands. Focus on emotional resonance and brand voice.","demand_level":"medium","salary_premium":"+20-40%"},{"name":"SEO Content Strategist","description":"Plan and execute content that ranks. Now requires AI fluency plus editorial judgment.","demand_level":"medium","salary_premium":"+15-25%"},{"name":"Scriptwriter / Screenwriter","description":"Write for video, podcasts, and film. AI scripts lack human nuance and cultural specificity.","demand_level":"medium","salary_premium":"+30-50%"}]'::jsonb,
  future_opportunities = '[{"role":"AI Content Strategist","description":"Design how organizations use AI for content while maintaining quality and brand voice. Emerging role.","timeline":"2-4 years","transition_difficulty":"easy"},{"role":"Brand Consultant","description":"Advise companies on voice, messaging, and content strategy. Leverages writing expertise at a strategic level.","timeline":"5-7 years","transition_difficulty":"medium"},{"role":"UX Writer / Content Designer","description":"Write microcopy, error messages, and interface text. Natural transition for writers in tech.","timeline":"2-3 years","transition_difficulty":"easy"},{"role":"Journalist / Investigative Reporter","description":"Pivot to journalism where original reporting and human judgment are irreplaceable.","timeline":"3-5 years","transition_difficulty":"medium"}]'::jsonb
WHERE slug = 'content-writer';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":6,"tools_to_master":["ChatGPT","Claude","Jasper","HubSpot AI","Surfer SEO","Midjourney","Canva AI","Meta Advantage+"],"augmented_tasks":"AI automates A/B testing, audience segmentation, ad creative generation, and performance reporting. Marketers use AI for campaign ideation, copy variation, and predictive analytics. Chatbots handle lead qualification and nurturing at scale.","automated_tasks":"Routine ad bidding, basic email marketing, simple social media scheduling, and standard performance reports are heavily automated. Entry-level campaign management and basic SEO are being commoditized by AI tools."}'::jsonb,
  specialty_tracks = '[{"name":"Growth Marketing Manager","description":"Focus on acquisition, retention, and revenue metrics. Heavy experimentation and data analysis.","demand_level":"high","salary_premium":"+30-50%"},{"name":"Brand Marketing Manager","description":"Build brand equity, positioning, and emotional connection. Less automatable than performance marketing.","demand_level":"medium","salary_premium":"+20-30%"},{"name":"Marketing Analytics Manager","description":"Own marketing data, attribution models, and predictive analytics. Technical and high-value.","demand_level":"high","salary_premium":"+40-60%"},{"name":"Influencer / Community Manager","description":"Build and manage creator relationships and community engagement. Human-centric and relationship-driven.","demand_level":"high","salary_premium":"+15-25%"}]'::jsonb,
  future_opportunities = '[{"role":"Chief Marketing Officer","description":"Lead marketing strategy and brand vision. Natural progression for senior marketers.","timeline":"8-12 years","transition_difficulty":"medium"},{"role":"AI Marketing Strategist","description":"Design how companies integrate AI into marketing workflows while maintaining brand integrity.","timeline":"3-5 years","transition_difficulty":"easy"},{"role":"Product Marketing Manager","description":"Bridge product and marketing. Strong fit for marketers who understand tech products.","timeline":"4-6 years","transition_difficulty":"medium"},{"role":"Founder (D2C / E-commerce)","description":"Start your own brand using marketing expertise. Thai e-commerce is booming.","timeline":"5-10 years","transition_difficulty":"hard"}]'::jsonb
WHERE slug = 'marketing-specialist';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":8,"tools_to_master":["QuickBooks AI","Xero","SAP AI","ChatGPT","Claude","Microsoft Copilot","Dext","Receipt Bank"],"augmented_tasks":"AI automates data entry, reconciliation, and basic report generation. Accountants use AI for anomaly detection, fraud identification, and predictive cash flow analysis. Tax software with AI handles routine filings and deductions.","automated_tasks":"Bookkeeping, invoice processing, basic reconciliation, standard tax preparation, and routine compliance reporting are heavily automated. Entry-level data entry and basic ledger maintenance face severe displacement."}'::jsonb,
  specialty_tracks = '[{"name":"Forensic Accountant","description":"Investigate financial fraud, disputes, and legal cases. Requires analytical judgment AI cannot replicate.","demand_level":"medium","salary_premium":"+40-60%"},{"name":"Tax Strategist / Advisor","description":"Design complex tax strategies for high-net-worth individuals and corporations. High-value advisory.","demand_level":"high","salary_premium":"+50-80%"},{"name":"Financial Controller","description":"Oversee accounting operations, financial reporting, and compliance for organizations.","demand_level":"high","salary_premium":"+60-100%"},{"name":"ESG / Sustainability Accountant","description":"Measure and report on environmental and social metrics. Growing with regulatory requirements.","demand_level":"high","salary_premium":"+30-50%"}]'::jsonb,
  future_opportunities = '[{"role":"Financial Analyst","description":"Transition to analysis and advisory. Natural path for accountants with strong analytical skills.","timeline":"3-5 years","transition_difficulty":"easy"},{"role":"CFO","description":"Chief Financial Officer. Ultimate progression for finance professionals with business acumen.","timeline":"10-15 years","transition_difficulty":"hard"},{"role":"AI Implementation Consultant","description":"Help firms adopt AI accounting tools and redesign workflows. Combines accounting with tech fluency.","timeline":"3-5 years","transition_difficulty":"medium"},{"role":"Forensic Investigator","description":"Specialize in fraud detection and financial crime investigation. High demand in corporate Thailand.","timeline":"5-7 years","transition_difficulty":"medium"}]'::jsonb
WHERE slug = 'accountant';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":9,"tools_to_master":["Zendesk AI","Intercom Fin","Freshdesk AI","ChatGPT","Claude","Salesforce Einstein","Tidio","Landbot"],"augmented_tasks":"AI handles tier-1 inquiries, drafts responses, and routes complex issues to the right agent. Human agents focus on escalations, emotional de-escalation, and complex problem-solving. AI provides real-time suggestions and knowledge base lookups.","automated_tasks":"Password resets, order tracking, refund processing, FAQ responses, and basic troubleshooting are almost fully automated. Simple inbound call handling and live chat for routine issues face near-total displacement."}'::jsonb,
  specialty_tracks = '[{"name":"Technical Support Specialist","description":"Handle complex product issues requiring deep technical knowledge. Less automatable than general support.","demand_level":"high","salary_premium":"+30-50%"},{"name":"Customer Success Manager","description":"Proactively ensure customers achieve outcomes. Strategic and relationship-driven, not transactional.","demand_level":"high","salary_premium":"+40-60%"},{"name":"VIP / Enterprise Support","description":"Support high-value accounts with white-glove service. Requires business acumen and diplomacy.","demand_level":"medium","salary_premium":"+30-40%"},{"name":"AI Trainer / Conversation Designer","description":"Train and optimize AI chatbots. New role combining support expertise with AI fluency.","demand_level":"high","salary_premium":"+20-40%"}]'::jsonb,
  future_opportunities = '[{"role":"Customer Success Manager","description":"Transition from reactive support to proactive success. Natural and recommended path.","timeline":"2-3 years","transition_difficulty":"easy"},{"role":"Operations Manager","description":"Manage support operations, workforce planning, and quality assurance. Common progression.","timeline":"4-6 years","transition_difficulty":"medium"},{"role":"AI Conversation Designer","description":"Design chatbot flows and train AI agents. Uses support expertise in a new way.","timeline":"1-2 years","transition_difficulty":"easy"},{"role":"Sales Development Representative","description":"Pivot to sales using communication skills and product knowledge. Common in SaaS companies.","timeline":"2-3 years","transition_difficulty":"easy"}]'::jsonb
WHERE slug = 'customer-service-representative';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":9,"tools_to_master":["DeepL","ChatGPT","Google Translate","Smartcat","MemoQ","Trados","Lokalise AI","Phrase"],"augmented_tasks":"AI provides first-pass translation, terminology consistency, and post-editing suggestions. Translators focus on cultural adaptation, creative translation, and quality assurance. AI handles bulk translation and glossary management.","automated_tasks":"General business translation, technical documentation, and standard correspondence for major language pairs are heavily automated. Basic website localization and app string translation are increasingly AI-driven."}'::jsonb,
  specialty_tracks = '[{"name":"Legal Translator","description":"Translate contracts, court documents, and legal texts. Requires legal knowledge and precision.","demand_level":"medium","salary_premium":"+40-60%"},{"name":"Medical Translator","description":"Translate clinical records, pharmaceutical documents, and medical device manuals. High stakes and regulated.","demand_level":"medium","salary_premium":"+50-70%"},{"name":"Literary / Creative Translator","description":"Translate novels, poetry, and creative works. Requires artistic sensibility and cultural depth.","demand_level":"low","salary_premium":"+20-40%"},{"name":"Localization Manager","description":"Manage translation projects, vendor relationships, and quality standards. Strategic role.","demand_level":"medium","salary_premium":"+30-50%"}]'::jsonb,
  future_opportunities = '[{"role":"Content Writer","description":"Transition to writing original content in target language. Natural for translators with strong writing skills.","timeline":"2-4 years","transition_difficulty":"easy"},{"role":"Localization Manager","description":"Manage global content strategy and translation workflows. Uses translation expertise at a strategic level.","timeline":"4-6 years","transition_difficulty":"medium"},{"role":"AI Post-Editing Specialist","description":"Specialize in refining AI translations to publication quality. Emerging hybrid role.","timeline":"1-2 years","transition_difficulty":"easy"},{"role":"Cross-Cultural Consultant","description":"Advise companies on cultural adaptation of products and content. Leverages deep cultural knowledge.","timeline":"5-7 years","transition_difficulty":"medium"}]'::jsonb
WHERE slug = 'translator';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":8,"tools_to_master":["Harvey AI","CoCounsel","Claude","ChatGPT","Relativity","LexisNexis+","Kira Systems","Luminance"],"augmented_tasks":"AI accelerates document review, contract analysis, legal research, and due diligence. Paralegals use AI for case law search, deposition summary, and discovery organization. AI drafts routine documents and checks for inconsistencies.","automated_tasks":"Routine document review, standard contract drafting, basic legal research, and form preparation are heavily automated. Entry-level discovery and due diligence work face severe displacement from AI platforms."}'::jsonb,
  specialty_tracks = '[{"name":"Litigation Support Specialist","description":"Manage e-discovery, trial preparation, and court filings. Requires procedural knowledge and attention to detail.","demand_level":"medium","salary_premium":"+20-30%"},{"name":"Corporate Paralegal","description":"Support M&A, compliance, and corporate governance. High-value work in Bangkok legal market.","demand_level":"medium","salary_premium":"+30-40%"},{"name":"IP Paralegal","description":"Specialize in patents, trademarks, and intellectual property. Technical and detail-oriented.","demand_level":"medium","salary_premium":"+25-35%"},{"name":"Legal Operations Manager","description":"Manage legal department workflows, technology, and vendor relationships. Strategic and growing field.","demand_level":"high","salary_premium":"+40-60%"}]'::jsonb,
  future_opportunities = '[{"role":"Lawyer","description":"Pursue law degree and bar admission. Many paralegals use their experience as a foundation.","timeline":"4-6 years","transition_difficulty":"hard"},{"role":"Legal Operations Manager","description":"Manage legal tech and workflows. Natural progression for tech-savvy paralegals.","timeline":"4-6 years","transition_difficulty":"medium"},{"role":"Compliance Officer","description":"Ensure organizational compliance with regulations. Uses legal knowledge in a business context.","timeline":"3-5 years","transition_difficulty":"easy"},{"role":"Contract Manager","description":"Manage contract lifecycle and negotiation. High demand in corporate Thailand.","timeline":"2-4 years","transition_difficulty":"easy"}]'::jsonb
WHERE slug = 'paralegal';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":2,"tools_to_master":["ChatGPT","Khanmigo","Canva","Google Classroom","Nearpod","Kahoot AI","Gradescope","Curipod"],"augmented_tasks":"AI generates lesson plans, creates differentiated materials, and provides personalized practice for students. Teachers use AI for grading assistance, parent communication, and administrative tasks. AI tutoring tools supplement but do not replace classroom instruction.","automated_tasks":"Basic worksheet generation, routine grading of objective questions, and standard report writing are partially automated. However, mentorship, classroom management, and social-emotional learning remain fundamentally human."}'::jsonb,
  specialty_tracks = '[{"name":"STEM Teacher","description":"Teach math, science, coding, or robotics. Highest demand and most future-proof teaching area.","demand_level":"high","salary_premium":"+20-30%"},{"name":"Special Education Teacher","description":"Work with students with learning differences. Requires specialized training and deep empathy.","demand_level":"high","salary_premium":"+20-30%"},{"name":"International School Teacher","description":"Teach in English at international schools. Requires Western credentials and pays significantly more.","demand_level":"high","salary_premium":"+100-200%"},{"name":"EdTech Specialist","description":"Integrate technology into teaching and train other educators. Bridge between teaching and technology.","demand_level":"medium","salary_premium":"+15-25%"},{"name":"Online Course Creator","description":"Build and sell digital courses. Leverages teaching expertise for scalable income.","demand_level":"medium","salary_premium":"+50-100% (variable)"}]'::jsonb,
  future_opportunities = '[{"role":"School Administrator / Principal","description":"Lead schools and educational programs. Natural progression for experienced teachers.","timeline":"8-12 years","transition_difficulty":"medium"},{"role":"Curriculum Designer","description":"Design educational programs and materials at scale. Uses teaching expertise in a product context.","timeline":"5-7 years","transition_difficulty":"easy"},{"role":"EdTech Founder","description":"Build educational technology for Thai market. DEPA and education ministry support edtech startups.","timeline":"5-10 years","transition_difficulty":"hard"},{"role":"Corporate Trainer / L&D Manager","description":"Design training programs for companies. High demand in Thai corporate sector.","timeline":"4-6 years","transition_difficulty":"easy"}]'::jsonb
WHERE slug = 'teacher';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":1,"tools_to_master":["Epic Systems","Cerner","AI-powered diagnostics","ChatGPT","Telemedicine platforms","Remote patient monitoring","Smart IV pumps","Robotic surgery assistants"],"augmented_tasks":"AI assists with diagnostic imaging, patient monitoring, and drug interaction checks. Nurses use AI for scheduling, documentation, and predictive alerts. Telemedicine platforms expand reach. However, physical care, emotional support, and clinical judgment remain irreplaceable.","automated_tasks":"Basic vital sign monitoring, routine documentation, and medication reminders are partially automated. Administrative tasks like scheduling and billing are increasingly AI-assisted. Direct patient care cannot be automated."}'::jsonb,
  specialty_tracks = '[{"name":"ICU / Critical Care Nurse","description":"Care for critically ill patients in intensive care. High stakes and high compensation.","demand_level":"high","salary_premium":"+30-50%"},{"name":"Operating Room Nurse","description":"Support surgical teams during operations. Requires specialized training and precision.","demand_level":"high","salary_premium":"+30-50%"},{"name":"Nurse Practitioner","description":"Advanced practice with diagnostic and prescribing authority. Requires master degree.","demand_level":"high","salary_premium":"+60-100%"},{"name":"Nurse Educator","description":"Train next generation of nurses. Critical for addressing nursing shortages.","demand_level":"high","salary_premium":"+20-30%"}]'::jsonb,
  future_opportunities = '[{"role":"Nurse Practitioner / Advanced Practice Nurse","description":"Pursue advanced degree for independent practice authority. Highest clinical nursing role.","timeline":"4-6 years","transition_difficulty":"medium"},{"role":"Nurse Manager / Director","description":"Lead nursing departments and units. Natural progression for experienced nurses.","timeline":"6-10 years","transition_difficulty":"medium"},{"role":"Healthcare Administrator","description":"Manage hospital operations and strategy. Combines clinical knowledge with business skills.","timeline":"8-12 years","transition_difficulty":"hard"},{"role":"Telehealth Nurse","description":"Provide remote care via digital platforms. Growing with Thailand digital health initiatives.","timeline":"2-3 years","transition_difficulty":"easy"}]'::jsonb
WHERE slug = 'nurse';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":1,"tools_to_master":["Solar design software","EV charging installation guides","PLC programming","BIM","Smart home systems","Thermal imaging","Drone inspection","AI diagnostic tools"],"augmented_tasks":"AI assists with load calculations, solar panel optimization, and predictive maintenance. Smart diagnostic tools help identify electrical faults faster. BIM software streamlines installation planning. However, physical installation, troubleshooting, and safety work require human presence.","automated_tasks":"Basic load calculations, standard wiring diagrams, and routine inspection scheduling are partially automated. However, the physical work of installation, repair, and on-site problem-solving cannot be automated."}'::jsonb,
  specialty_tracks = '[{"name":"Solar PV Installer","description":"Install and maintain solar panels and inverters. Booming with Thailand renewable energy push.","demand_level":"high","salary_premium":"+30-50%"},{"name":"EV Charging Installer","description":"Install electric vehicle charging infrastructure. New and rapidly growing specialty.","demand_level":"high","salary_premium":"+40-60%"},{"name":"Industrial Electrician","description":"Maintain complex electrical systems in factories and plants. High skill and high pay.","demand_level":"high","salary_premium":"+30-50%"},{"name":"Smart Home / Automation Electrician","description":"Install IoT devices, smart panels, and home automation systems. Growing consumer demand.","demand_level":"medium","salary_premium":"+20-30%"}]'::jsonb,
  future_opportunities = '[{"role":"Electrical Contractor / Business Owner","description":"Start your own electrical contracting business. Natural progression for experienced electricians.","timeline":"5-8 years","transition_difficulty":"medium"},{"role":"Renewable Energy Technician","description":"Specialize in wind, solar, and energy storage systems. Aligns with Thailand green energy goals.","timeline":"3-5 years","transition_difficulty":"easy"},{"role":"Energy Consultant","description":"Advise on energy efficiency and renewable solutions. Combines technical skills with business knowledge.","timeline":"6-8 years","transition_difficulty":"medium"},{"role":"Automation / Controls Engineer","description":"Transition to industrial automation and PLC programming. Higher pay and indoor work.","timeline":"4-6 years","transition_difficulty":"medium"}]'::jsonb
WHERE slug = 'electrician';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":7,"tools_to_master":["Route optimization AI","Fleet management software","GPS analytics","Tesla Autopilot","Waymo","Platooning systems","Dash cam AI","Load matching platforms"],"augmented_tasks":"AI optimizes routes, predicts maintenance needs, and matches loads to drivers. Fleet management software improves efficiency. Advanced driver assistance systems (ADAS) reduce fatigue and improve safety. However, full autonomy faces regulatory and safety barriers.","automated_tasks":"Route planning, load matching, and basic logistics coordination are increasingly automated. Long-haul highway driving may be partially automated in the next decade. Last-mile delivery is being disrupted by drones and autonomous vehicles in some markets."}'::jsonb,
  specialty_tracks = '[{"name":"Last-Mile Delivery Driver","description":"Deliver packages in urban areas. Growing with e-commerce boom in Thailand.","demand_level":"high","salary_premium":"same"},{"name":"Heavy Machinery Operator","description":"Operate cranes, excavators, and specialized equipment. Requires certification and skill.","demand_level":"high","salary_premium":"+30-50%"},{"name":"Fleet Supervisor","description":"Manage driver teams, schedules, and compliance. Strategic role as fleets grow.","demand_level":"medium","salary_premium":"+20-30%"},{"name":"Hazmat / Specialized Transport","description":"Transport dangerous goods or oversized loads. Requires special licensing and pays premium.","demand_level":"medium","salary_premium":"+40-60%"}]'::jsonb,
  future_opportunities = '[{"role":"Fleet Operations Manager","description":"Manage logistics operations, technology, and compliance. Natural progression for experienced drivers.","timeline":"5-7 years","transition_difficulty":"medium"},{"role":"Logistics Coordinator","description":"Plan and coordinate freight movements. Uses driving experience in an office role.","timeline":"3-5 years","transition_difficulty":"easy"},{"role":"EV / Autonomous Vehicle Monitor","description":"Monitor self-driving trucks and take over in complex situations. Emerging role.","timeline":"3-5 years","transition_difficulty":"easy"},{"role":"Transportation Business Owner","description":"Start your own logistics or delivery company. Common entrepreneurial path.","timeline":"5-10 years","transition_difficulty":"hard"}]'::jsonb
WHERE slug = 'truck-driver';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":6,"tools_to_master":["ChatGPT","Claude","Perplexity","Otter.ai","Descript","Runway ML","Midjourney","Canva AI"],"augmented_tasks":"AI helps with research, transcription, first drafts, and data analysis. Journalists use AI for background research, fact-checking, and identifying trends. AI-generated summaries help process large document sets. Multimedia AI tools streamline video and audio production.","automated_tasks":"Earnings reports, sports recaps, weather updates, and routine event coverage are increasingly automated. Basic data journalism and templated news briefs face displacement. However, investigative reporting, source relationships, and on-the-ground coverage remain human."}'::jsonb,
  specialty_tracks = '[{"name":"Investigative Journalist","description":"Uncover corruption, injustice, and hidden stories. The most durable and prestigious journalism track.","demand_level":"medium","salary_premium":"+30-50%"},{"name":"Data Journalist","description":"Use data analysis and visualization to tell stories. Combines journalism with technical skills.","demand_level":"medium","salary_premium":"+20-40%"},{"name":"Multimedia Journalist","description":"Produce video, podcasts, and interactive content. High demand in digital-native outlets.","demand_level":"high","salary_premium":"+20-30%"},{"name":"Business / Tech Reporter","description":"Cover companies, markets, and technology. Requires domain expertise and pays well.","demand_level":"medium","salary_premium":"+30-50%"}]'::jsonb,
  future_opportunities = '[{"role":"Editor / News Director","description":"Lead editorial teams and set coverage priorities. Natural progression for experienced journalists.","timeline":"7-10 years","transition_difficulty":"medium"},{"role":"Content Strategist","description":"Advise organizations on content and storytelling. Uses journalism skills in a business context.","timeline":"4-6 years","transition_difficulty":"easy"},{"role":"Documentary Filmmaker","description":"Create long-form video content. Leverages reporting skills in a visual medium.","timeline":"5-8 years","transition_difficulty":"medium"},{"role":"Independent Publisher / Substack Writer","description":"Build your own audience and monetize directly. Growing model for investigative journalists.","timeline":"3-5 years","transition_difficulty":"medium"}]'::jsonb
WHERE slug = 'journalist';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":6,"tools_to_master":["Bloomberg Terminal AI","ChatGPT","Claude","Python","Tableau","Power BI","AlphaSense","Kensho"],"augmented_tasks":"AI automates financial modeling, sentiment analysis, and routine report generation. Analysts use AI for earnings call transcription, competitor monitoring, and scenario analysis. Algorithmic trading handles execution, freeing analysts for strategy.","automated_tasks":"Basic spreadsheet modeling, standard valuation templates, routine earnings summaries, and simple trend analysis are heavily automated. Entry-level number-crunching and data gathering face displacement from AI and outsourcing."}'::jsonb,
  specialty_tracks = '[{"name":"Investment Banking Analyst","description":"Work on M&A, IPOs, and corporate finance. Highest prestige and compensation in finance.","demand_level":"high","salary_premium":"+100-200%"},{"name":"ESG Analyst","description":"Evaluate environmental, social, and governance factors. Growing with sustainable investing.","demand_level":"high","salary_premium":"+30-50%"},{"name":"Quantitative Analyst","description":"Build mathematical models for trading and risk. Requires strong programming and math skills.","demand_level":"high","salary_premium":"+80-150%"},{"name":"Private Equity Analyst","description":"Evaluate companies for acquisition and portfolio management. Strategic and high-impact.","demand_level":"high","salary_premium":"+100-200%"}]'::jsonb,
  future_opportunities = '[{"role":"Portfolio Manager","description":"Manage investment portfolios and make allocation decisions. Natural progression for senior analysts.","timeline":"6-10 years","transition_difficulty":"medium"},{"role":"CFO","description":"Chief Financial Officer. Ultimate business-side progression for finance professionals.","timeline":"10-15 years","transition_difficulty":"hard"},{"role":"Venture Capitalist","description":"Invest in startups and evaluate new markets. Common path for analysts with strong networks.","timeline":"7-10 years","transition_difficulty":"medium"},{"role":"Fintech Founder","description":"Start financial technology companies. Thai fintech is booming (SCB, KBANK, LINE BK).","timeline":"5-10 years","transition_difficulty":"hard"}]'::jsonb
WHERE slug = 'financial-analyst';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":5,"tools_to_master":["LinkedIn Recruiter AI","HireVue","Paradox Olivia","ChatGPT","Claude","Eightfold AI","Beamery","Greenhouse"],"augmented_tasks":"AI screens resumes, schedules interviews, and sources candidates. Recruiters use AI for drafting job descriptions, candidate outreach, and market mapping. Chatbots handle initial candidate questions. However, culture fit assessment and executive search remain human.","automated_tasks":"High-volume resume screening, initial candidate outreach, interview scheduling, and basic reference checks are heavily automated. Sourcing for junior roles is increasingly AI-driven. Relationship-based recruiting remains resilient."}'::jsonb,
  specialty_tracks = '[{"name":"Executive Search Consultant","description":"Recruit C-suite and senior leaders. Highest pay and most relationship-driven recruiting.","demand_level":"high","salary_premium":"+100-200%"},{"name":"Technical Recruiter","description":"Hire engineers, data scientists, and product managers. Requires understanding of tech roles.","demand_level":"high","salary_premium":"+40-60%"},{"name":"Employer Branding Specialist","description":"Build company reputation and attract talent through marketing and content. Strategic and creative.","demand_level":"medium","salary_premium":"+20-30%"},{"name":"Talent Acquisition Manager","description":"Lead recruiting strategy and team for organizations. Management track with broad impact.","demand_level":"high","salary_premium":"+60-100%"}]'::jsonb,
  future_opportunities = '[{"role":"Chief People Officer / VP HR","description":"Lead human resources and talent strategy. Natural progression for senior recruiters.","timeline":"8-12 years","transition_difficulty":"medium"},{"role":"HR Business Partner","description":"Align HR strategy with business objectives. Uses recruiting insight in a broader context.","timeline":"5-7 years","transition_difficulty":"easy"},{"role":"Talent Intelligence Analyst","description":"Use data and AI to predict talent needs and market trends. Emerging strategic role.","timeline":"3-5 years","transition_difficulty":"easy"},{"role":"HR Tech Consultant","description":"Advise companies on recruiting technology and AI implementation. Combines recruiting with tech fluency.","timeline":"4-6 years","transition_difficulty":"medium"}]'::jsonb
WHERE slug = 'hr-recruiter';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":7,"tools_to_master":["Adobe Firefly","Midjourney","DALL-E 3","Runway ML","Topaz Photo AI","Luminar Neo","After Effects","DaVinci Resolve"],"augmented_tasks":"AI assists with editing, color grading, background replacement, and image enhancement. Photographers use AI for culling, organizing, and basic retouching. Generative AI creates concept art and mockups. However, composition, timing, and human connection remain irreplaceable.","automated_tasks":"Stock photography, basic product shots on white backgrounds, and standard portrait retouching are heavily disrupted by AI. Simple event documentation and real estate photography face competition from AI-generated and automated alternatives."}'::jsonb,
  specialty_tracks = '[{"name":"Commercial / Product Photographer","description":"Shoot products for e-commerce and advertising. High demand in Thai digital economy.","demand_level":"high","salary_premium":"+30-50%"},{"name":"Wedding / Event Photographer","description":"Capture once-in-a-lifetime moments. Emotional and irreplaceable human service.","demand_level":"high","salary_premium":"+40-80%"},{"name":"Documentary / Photojournalist","description":"Tell real stories through images. Requires presence, timing, and ethical judgment.","demand_level":"low","salary_premium":"+10-20%"},{"name":"Drone / Aerial Photographer","description":"Capture aerial imagery for real estate, tourism, and construction. Requires pilot license.","demand_level":"medium","salary_premium":"+30-50%"},{"name":"Video / Cinematographer","description":"Create video content for brands, events, and social media. Strong demand in digital marketing.","demand_level":"high","salary_premium":"+50-100%"}]'::jsonb,
  future_opportunities = '[{"role":"Creative Director","description":"Lead visual strategy for brands and campaigns. Uses photography expertise at a strategic level.","timeline":"7-10 years","transition_difficulty":"medium"},{"role":"Videographer / Filmmaker","description":"Transition to video where AI disruption is less advanced. Natural skills transfer.","timeline":"2-4 years","transition_difficulty":"easy"},{"role":"Content Creator / Influencer","description":"Build personal brand and monetize through social media. Growing path in Thailand.","timeline":"2-5 years","transition_difficulty":"medium"},{"role":"Visual AI Consultant","description":"Help brands use AI tools for visual content while maintaining quality. Emerging hybrid role.","timeline":"3-5 years","transition_difficulty":"easy"}]'::jsonb
WHERE slug = 'photographer';

UPDATE public.career_survival SET
  ai_impact = '{"automation_risk":3,"tools_to_master":["Harvey AI","CoCounsel","Claude","ChatGPT","LexisNexis+","Westlaw Edge","Kira Systems","ContractPodAi"],"augmented_tasks":"AI accelerates legal research, contract drafting, and document review. Lawyers use AI for case law search, precedent analysis, and due diligence. AI-generated first drafts save time. However, strategy, negotiation, and courtroom advocacy remain deeply human.","automated_tasks":"Routine legal research, standard contract templates, basic document review, and initial case summaries are increasingly automated. Paralegal-level document processing and form drafting face significant AI disruption."}'::jsonb,
  specialty_tracks = '[{"name":"Corporate / M&A Lawyer","description":"Advise on mergers, acquisitions, and corporate transactions. Highest-paying legal specialty.","demand_level":"high","salary_premium":"+100-200%"},{"name":"Intellectual Property Lawyer","description":"Protect patents, trademarks, and creative works. Critical for tech and media companies.","demand_level":"high","salary_premium":"+60-100%"},{"name":"Litigation / Dispute Resolution","description":"Represent clients in court and arbitration. Requires advocacy skills and strategic thinking.","demand_level":"high","salary_premium":"+80-150%"},{"name":"Data Privacy / Cybersecurity Lawyer","description":"Advise on GDPR, PDPA, and cybersecurity compliance. Fastest-growing legal specialty.","demand_level":"high","salary_premium":"+60-100%"},{"name":"International Arbitration Lawyer","description":"Handle cross-border disputes. Requires multilingual skills and pays premium.","demand_level":"medium","salary_premium":"+100-200%"}]'::jsonb,
  future_opportunities = '[{"role":"Partner at Law Firm","description":"Equity partner with profit share. Ultimate progression for private practice lawyers.","timeline":"8-15 years","transition_difficulty":"hard"},{"role":"General Counsel","description":"Lead legal function for a corporation. Strategic and high-status in-house role.","timeline":"10-15 years","transition_difficulty":"hard"},{"role":"Legal Tech Founder","description":"Build AI legal tools and legal tech startups. Growing sector with venture interest.","timeline":"5-10 years","transition_difficulty":"hard"},{"role":"Judge / Arbitrator","description":"Transition to judiciary or private arbitration. Prestigious and respected path.","timeline":"15-20 years","transition_difficulty":"hard"}]'::jsonb
WHERE slug = 'lawyer';
