-- Add extra_prompt_responses JSONB column to path_reflections
-- This stores the student's responses to AI-generated daily reflection prompts

ALTER TABLE public.path_reflections
ADD COLUMN IF NOT EXISTS extra_prompt_responses JSONB DEFAULT NULL;

COMMENT ON COLUMN public.path_reflections.extra_prompt_responses IS 'Array of student responses to extra daily reflection prompts generated by AI';
