// --- Map Lobby Functions ---
//
// Lobbies are admin-created rooms that gate access to a single map. Membership
// grants access to node content and lets lobbymates see each other's progress.

import { createClient } from "@/utils/supabase/server";
import type {
  LobbyAccessTier,
  MapLobby,
  MapLobbyWithCount,
  LobbyRosterEntry,
  LobbyPresenceEntry,
  NodeProgressStatus,
} from "@/types/lobby";

interface ProfileFields {
  full_name: string | null;
  avatar_url: string | null;
}

interface ProgressRow {
  user_id: string;
  node_id: string;
  node_title: string | null;
  status: NodeProgressStatus;
  arrived_at: string | null;
}

/**
 * Admin: create a lobby for a map. The join code is generated by Postgres.
 */
export const createLobby = async (
  mapId: string,
  name: string,
  accessTier: LobbyAccessTier = "full"
): Promise<MapLobby> => {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    throw new Error("Must be authenticated to create a lobby");
  }

  const { data, error } = await supabase
    .from("map_lobbies")
    .insert({
      map_id: mapId,
      name,
      access_tier: accessTier,
      created_by: user.id,
    })
    .select()
    .single();

  if (error) {
    console.error("Error creating lobby:", error);
    throw new Error("Failed to create lobby");
  }

  return data as MapLobby;
};

/**
 * Admin: all lobbies for a map, with member counts.
 */
export const getLobbiesForMap = async (
  mapId: string
): Promise<MapLobbyWithCount[]> => {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("map_lobbies")
    .select("*, lobby_members(count)")
    .eq("map_id", mapId)
    .order("created_at", { ascending: false });

  if (error) {
    console.error("Error fetching lobbies:", error);
    throw new Error("Failed to load lobbies");
  }

  return (data ?? []).map((row) => {
    const { lobby_members: memberCounts, ...lobby } = row as MapLobby & {
      lobby_members: { count: number }[] | null;
    };
    return {
      ...lobby,
      member_count: memberCounts?.[0]?.count ?? 0,
    };
  });
};

/**
 * Admin: roster for one lobby, including each member's current node.
 */
export const getLobbyRoster = async (
  lobbyId: string
): Promise<LobbyRosterEntry[]> => {
  const supabase = await createClient();

  const { data: lobby, error: lobbyError } = await supabase
    .from("map_lobbies")
    .select("map_id")
    .eq("id", lobbyId)
    .single();

  if (lobbyError || !lobby) {
    console.error("Error loading lobby:", lobbyError);
    throw new Error("Failed to load lobby");
  }

  const { data: members, error: membersError } = await supabase
    .from("lobby_members")
    .select("user_id, joined_at, profiles(full_name, avatar_url)")
    .eq("lobby_id", lobbyId);

  if (membersError) {
    console.error("Error loading roster:", membersError);
    throw new Error("Failed to load roster");
  }

  const userIds = (members ?? []).map((m) => m.user_id as string);
  if (userIds.length === 0) return [];

  const progress = await fetchProgressForUsers(userIds, lobby.map_id as string);

  return (members ?? []).map((member) => {
    const profile = extractProfile(member.profiles);
    const rows = progress.filter((p) => p.user_id === member.user_id);
    const current = pickCurrentNode(rows);

    return {
      user_id: member.user_id as string,
      full_name: profile.full_name,
      avatar_url: profile.avatar_url,
      joined_at: member.joined_at as string,
      current_node_id: current?.node_id ?? null,
      current_node_title: current?.node_title ?? null,
      completed_count: rows.filter((r) => r.status === "passed").length,
    };
  });
};

/**
 * Admin: open or close a lobby. Closing blocks NEW joins only -- existing
 * members keep their access.
 */
export const setLobbyOpen = async (
  lobbyId: string,
  isOpen: boolean
): Promise<void> => {
  const supabase = await createClient();

  const { error } = await supabase
    .from("map_lobbies")
    .update({ is_open: isOpen })
    .eq("id", lobbyId);

  if (error) {
    console.error("Error updating lobby:", error);
    throw new Error("Failed to update lobby");
  }
};

/**
 * Admin: switch a lobby between the full map and the micro (free) tier.
 * Takes effect on the members' next page load -- nothing is copied onto the
 * membership rows, so the tier is always read from the lobby.
 */
export const setLobbyAccessTier = async (
  lobbyId: string,
  accessTier: LobbyAccessTier
): Promise<void> => {
  const supabase = await createClient();

  const { error } = await supabase
    .from("map_lobbies")
    .update({ access_tier: accessTier })
    .eq("id", lobbyId);

  if (error) {
    console.error("Error updating lobby access tier:", error);
    throw new Error("Failed to update lobby access tier");
  }
};

/**
 * The current user's lobby for a map, or null if they are not a member.
 * This is the membership check the map detail page gates on.
 */
export const getUserLobbyForMap = async (
  mapId: string
): Promise<MapLobby | null> => {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return null;

  // Not maybeSingle(): nothing in the schema stops a user being a member of two
  // lobbies for one map (the UNIQUE constraint is on enrollments, not
  // memberships), and maybeSingle() throws on multiple rows -- which would
  // silently drop the user back to the code gate. Take the earliest join.
  const { data, error } = await supabase
    .from("map_lobbies")
    .select("*, lobby_members!inner(user_id, joined_at)")
    .eq("map_id", mapId)
    .eq("lobby_members.user_id", user.id)
    .order("created_at", { ascending: true })
    .limit(1);

  if (error) {
    console.error("Error checking lobby membership:", error);
    return null;
  }
  if (!data || data.length === 0) return null;

  const { lobby_members: _members, ...lobby } = data[0] as MapLobby & {
    lobby_members: unknown;
  };
  return lobby;
};

/**
 * Presence: exactly one entry per lobbymate, on the node they are working.
 * Returns [] when the viewer is not in a lobby for this map.
 */
export const getLobbyPresence = async (
  mapId: string
): Promise<LobbyPresenceEntry[]> => {
  const supabase = await createClient();

  const lobby = await getUserLobbyForMap(mapId);
  if (!lobby) return [];

  const { data: members, error } = await supabase
    .from("lobby_members")
    .select("user_id, profiles(full_name, avatar_url)")
    .eq("lobby_id", lobby.id);

  if (error) {
    console.error("Error loading lobby members:", error);
    return [];
  }

  const userIds = (members ?? []).map((m) => m.user_id as string);
  if (userIds.length === 0) return [];

  const [progress, firstNodeId] = await Promise.all([
    fetchProgressForUsers(userIds, mapId),
    fetchFirstNodeId(mapId),
  ]);

  return (members ?? [])
    .map((member): LobbyPresenceEntry | null => {
      const profile = extractProfile(member.profiles);
      const current = pickCurrentNode(
        progress.filter((p) => p.user_id === member.user_id)
      );

      // A member who has started nothing shows on the map's first node.
      const nodeId = current?.node_id ?? firstNodeId;
      if (!nodeId) return null;

      return {
        user_id: member.user_id as string,
        full_name: profile.full_name,
        avatar_url: profile.avatar_url,
        node_id: nodeId,
        status: current?.status ?? "not_started",
      };
    })
    .filter((entry): entry is LobbyPresenceEntry => entry !== null);
};

// --- internals ---

/**
 * Supabase types an embedded to-one relation as either an object or an array
 * depending on the inferred cardinality; normalize both shapes.
 */
const extractProfile = (raw: unknown): ProfileFields => {
  const profile = Array.isArray(raw) ? raw[0] : raw;
  const typed = profile as ProfileFields | null | undefined;
  return {
    full_name: typed?.full_name ?? null,
    avatar_url: typed?.avatar_url ?? null,
  };
};

const fetchProgressForUsers = async (
  userIds: string[],
  mapId: string
): Promise<ProgressRow[]> => {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("student_node_progress")
    .select("user_id, node_id, status, arrived_at, map_nodes!inner(map_id, title)")
    .in("user_id", userIds)
    .eq("map_nodes.map_id", mapId);

  if (error) {
    console.error("Error loading progress:", error);
    return [];
  }

  return (data ?? []).map((row) => {
    const node = Array.isArray(row.map_nodes) ? row.map_nodes[0] : row.map_nodes;
    return {
      user_id: row.user_id as string,
      node_id: row.node_id as string,
      node_title: (node as { title: string | null } | null)?.title ?? null,
      status: row.status as NodeProgressStatus,
      arrived_at: (row.arrived_at as string | null) ?? null,
    };
  });
};

const fetchFirstNodeId = async (mapId: string): Promise<string | null> => {
  const supabase = await createClient();

  // Nodes created in one batch share an identical created_at, so ordering by it
  // alone is non-deterministic and can pick an arbitrary node as "first". The id
  // tiebreaker makes the fallback stable across requests.
  const { data } = await supabase
    .from("map_nodes")
    .select("id")
    .eq("map_id", mapId)
    .order("created_at", { ascending: true })
    .order("id", { ascending: true })
    .limit(1)
    .maybeSingle();

  return (data?.id as string | undefined) ?? null;
};

/**
 * One node per member: the in_progress node, else submitted, else the most
 * recent passed node, else nothing (caller falls back to the map's first node).
 */
const pickCurrentNode = (rows: ProgressRow[]): ProgressRow | null => {
  if (rows.length === 0) return null;

  // A node the student is actively working is where they are. A student can
  // hold several in_progress rows at once (opening a node starts it, and they
  // may leave without finishing), so take the most recently arrived rather than
  // whichever row the database happened to return first.
  const inProgress = rows
    .filter((r) => r.status === "in_progress")
    .sort((a, b) => (b.arrived_at ?? "").localeCompare(a.arrived_at ?? ""));
  if (inProgress.length > 0) return inProgress[0];

  // Otherwise they have finished everything they have touched, so they belong
  // on the furthest one. `submitted` counts as finished here -- awaiting a
  // grade is not the same as still working, and this matches the trail ring,
  // which skips both `passed` and `submitted` when picking the current node.
  // Treating `submitted` as the current position would strand a student's
  // avatar on a node the ring has already advanced past.
  const finished = rows
    .filter((r) => r.status === "passed" || r.status === "submitted")
    .sort((a, b) => (b.arrived_at ?? "").localeCompare(a.arrived_at ?? ""));

  return finished[0] ?? null;
};
